### ISSUE TITLE
Priority: Test suite passing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#103]
@ricardopereira, every single PR submitted is passing, see https://github.com/ably/ably-ios/pulls

Before doing any more PRs, we need to ensure that:

- [x] All tests are passing in Travis CI
- [x] Test output is legible and easy to understand so that when tests fail, we can easily fix the problem

**Comment by ricardopereira** [comment]
@mattheworiordan You mean _is not passing_, right?
#85 has some fixes and is an important PR to verify if it is passing... well, but I notice right now that it is not passing. I will look at it.

**Comment by mattheworiordan** [comment]
Yes meant not passing, we need to have a test base that passes every time before we keep adding more tests

**Comment by ricardopereira** [comment]
@mattheworiordan Finally! One greeny 💚 https://travis-ci.org/ably/ably-ios/builds/94581801

**Comment by ricardopereira** [comment]
@mattheworiordan It seems like, sometimes in a random test, it stops with an error: `Invalid connection: com.apple.coresymbolicationd`. I have a folder with that name on my HD: `/System/Library/Caches/com.apple.coresymbolicationd` Something related with cache.

**Comment by mattheworiordan** [comment]
> It seems like, sometimes in a random test, it stops with an error: Invalid connection: com.apple.coresymbolicationd. I have a folder with that name on my HD: /System/Library/Caches/com.apple.coresymbolicationd Something related with cache

Ok, well good luck fixing that ;)
