### ISSUE TITLE
Auth: store TokenParams for subsequent authorisations

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#114]
> `Auth#authorise` (RSA10g) Stores the AuthOptions and TokenParams arguments as defaults for subsequent authorisations

`ARTAuth` does not store the AuthOptions/TokenParams for subsequent authorisations.

**Comment by ricardopereira** [comment]
@mattheworiordan About storing the `TokenParams`, should I store the `timestamp` field? As far as I know the `timestamp` should always have the time of the current request, right?

**Comment by mattheworiordan** [comment]
@ricardopereira that is a very good point, the `timestamp` field should not be stored.  I believe every other client library blindly stores the complete hash.  I will need to add an issue to all client libraries to exclude the `timestamp` and the `nonce`

**Comment by mattheworiordan** [comment]
Sorry, `nonce` is a TokenRequest field, ignore me.  However, @force@ attribute of `AuthOptions` should also not be stored as this would then mean every auth check would force a new authentication

**Comment by ricardopereira** [comment]
@mattheworiordan Yes, I was questioning me as well about `AuthOptions.force`. So, I will implement it without storing `timestamp` and `force`. :+1:

**Comment by mattheworiordan** [comment]
See https://github.com/ably/docs/commit/f768f0db76020d945cf34974ef7d14d36113f0cd
