### ISSUE TITLE
Auth: buffer of 15s for token expiry not implemented

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#115]
> `Auth#authorise` (RSA10c) Will not create a new token unless no previous token exists or current token has expired.

**Not implemented:**
_Please note that a buffer of 15s for token expiry is recommended to avoid race conditions where the token is valid at the time of the request, but invalid when it reaches the server. Therefore, we recommend that a token is considered expired 15s before the time field expires._

**Comment by tcard** [comment]
RSA10c is no longer in the spec.
