### ISSUE TITLE
RealtimeChannel: duplicated `publish` method

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#127]
**Code completion:**

<img width="659" alt="screen shot 2016-01-12 at 19 58 00" src="https://cloud.githubusercontent.com/assets/3541185/12293767/a2987d22-b9ed-11e5-8d7f-8e320bdd1e74.png">

The `RestChannel` is the base class of the `RealtimeChannel`. `RestChannel` has 4 publish methods that we already discussed on #121.

**Problem:**
The `RealtimeChannel` does not override those methods and use their own. It should override them and avoid calling the super implementation.

IMO, we should fix #121 first.

**Comment by mattheworiordan** [comment]
Agreed that #121 should be fixed first

**Comment by tcard** [comment]
I think the deeper problem is, why is RealtimeChannel inheriting from RestChannel? You can't use a RealtimeChannel as a RestChannel. If anything, both should inherit from a BaseChannel or implement a Channel protocol.

I strongly think that this should be fixed.

**Comment by mattheworiordan** [comment]
> I think the deeper problem is, why is RealtimeChannel inheriting from RestChannel

This is mostly because they share functionality such as `history`.  However, as you say, that could be part of the BaseChannel implementation instead.

**Comment by tcard** [comment]
To reuse code, it is a very well-established "principle" to use composition over inheritance. Anyway, to not get sucked into the rabbit hole, I would be happy with inheriting from a BaseChannel.

**Comment by mattheworiordan** [comment]
> To reuse code, it is a very well-established "principle" to use composition over inheritance.

Sure, we [do that in our Ably libraries](https://github.com/ably/ably-ruby/blob/master/lib/ably/realtime/channel.rb#L32-L36). If that's easy enough to do in Objective-C, sure, although I suspect we're largely using inheritance elsewhere

**Comment by ricardopereira** [comment]
Yes, it is largely using inheritance, e.g.: `ARTBaseMessage`.
I liked the use composition to fix this more than the `ARTBaseChannel` but I can do it for now.

@tcard So you mean something like `ARTChannelHistory`?

**Comment by tcard** [comment]
@ricardopereira I guess. Or even RealtimeChannel having a RestChannel property, because AFAIK RealtimeChannel just calls the REST API for history, right?

**Comment by ricardopereira** [comment]
Yes, you right.

**Comment by tcard** [comment]
Fixed by 97f0b16.
