### ISSUE TITLE
ARTPayload: class review

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#130]
- Change `payload` property to `data`:
```
message.payload.payload --> message.data
```

 - ARTPayload has an `encoding` property and `ARTBaseMessage` (that uses the ARTPayload class) has an `encoding` property as well. _Confusing_

**Comment by mattheworiordan** [comment]
Why is this not simply `message.data` like every other library?

**Comment by ricardopereira** [comment]
Updated

**Comment by ricardopereira** [comment]
@tcard Is this fixed, right? Can I close?

**Comment by tcard** [comment]
Yep, fixed!
