### ISSUE TITLE
Realtime: implement ARTConnection & ARTConnectionDetails

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#132]
- [x] [Connection](http://docs.ably.io/client-lib-development-guide/features/#RTN1)
 - [x] [ConnectionStateChange](http://docs.ably.io/client-lib-development-guide/features/#TA1)
 - [x] [ConnectionDetails](http://docs.ably.io/client-lib-development-guide/features/#CD1)

**Comment by mattheworiordan** [comment]
@tcard you mentioned you have worked on implementing the correct types, will it address any of the above?

**Comment by tcard** [comment]
Not really, no. I basically took a look at Message and related types, but didn't get anything done beyond a few notes, I had been mainly reading stuff (Ably code, Ably docs and iOS docs).
