### ISSUE TITLE
RealtimeChannel: attach is inconsistent with the API

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#189]
`attach` is returning an `ARTErrorInfo`.

Callback not implemented and the language permits:
> (RTL4d) If the language permits, a callback can be provided that is called when the channel is attached successfully or the attach fails and the the ErrorInfo error is passed as an argument to the callback.

**Comment by mattheworiordan** [comment]
Thanks, this is quite useful functionality so we should aim to implement this.

**Comment by tcard** [comment]
Fixed by #204.
