### ISSUE TITLE
No visible @interface for 'ARTRealtime' declares the selector 'subscribeToStateChanges:'

### ISSUE THREAD

**Issue by stannedelchev** [ably/ably-ios#20]
I'm using the connection code from README.md, but I keep getting the error above.

     ARTRealtime * client = [[ARTRealtime alloc] initWithKey:@"xxxxx"];
     [client subscribeToStateChanges:^(ARTRealtimeConnectionState state) {
         if (state == ARTRealtimeConnected) {
             // you are connected
         }
     }];

What's the recommended way to subscribe to connection changes? Is using `EventEmitter` ok?

    ARTRealtime * client = [[ARTRealtime alloc] initWithKey:@"xxxx"];
    [client.eventEmitter on:^(ARTRealtimeConnectionState state) {
        NSLog(@"OK");
    }];

Library is installed via podfile:

    use_frameworks!

    target 'demo-ios' do
            pod "ably", :git => 'https://github.com/ably/ably-ios.git', :commit => '006d61ba4c8c2572e5e1e91d786bee6c6800ad29'
    end

**Comment by mattheworiordan** [comment]
@fealebenpae are you able to help with this?

**Comment by fealebenpae** [comment]
`-[ARTRealTime subscribeToStateChanges:]` is a private method that the event emitter calls internally. You can use the event emitter to monitor state changes. The "state" attribute on `ARTRealtime` is Key Value Observing-compatible, so you can use Cocoa's [KVO methods](http://nshipster.com/key-value-observing/) to observe state changes as well.

**Comment by stannedelchev** [comment]
@fealebenpae thanks for the info.

@mattheworiordan It would be nice to have some up-to-date documentation for the iOS lib. There is nothing on docs.ably.io at this point and IMO the README is not sufficient.

**Comment by ricardopereira** [comment]
Currently it uses the ARTEventEmitter: https://github.com/ably/ably-ios/blob/2398b9580d6aaef45ca91c01a99160cf09bbd4d9/Source/ARTEventEmitter.h#L22
