### ISSUE TITLE
`ARTAuth` dependes on `ARTRest` and it shouldn't

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#27]
`ARTAuth` dependes on `ARTRest` and it shouldn't because it difficult's the testing process.

`ARTAuth` needs `ARTRest` instance for:
 - Logger
 - HttpExecutor
 - BaseURL
 - Default Encoder
 - Server Time request

**Comment by mattheworiordan** [comment]
@ricardopereira generally we have had a generic HTTP library for all HTTP actions, but not depending on ARTAuth may be difficult as the logger, encoders, server time and URLs are generally common functionality.  I am sure you will figure out what is best...

**Comment by ricardopereira** [comment]
This doesn't make sense anymore.
