### ISSUE TITLE
Update `podspec` when CocoaPods v1.0 is released in production

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#290]
CocoaPods 1.0 Migration Guide: http://blog.cocoapods.org/CocoaPods-1.0/

**Comment by ricardopereira** [comment]
CocoaPods/CocoaPods#5006

**Comment by mattheworiordan** [comment]
@tcard @ricardopereira can one of you try and deploy the pod now as Ably?  See https://cocoapods.org/?q=Ably.  Note if this works, we then need to deprecate AblyRealtime and update the documentation, but let us be sure that the Ably pod works first.  Also, prob time for a version bump?

**Comment by mattheworiordan** [comment]
Also, see https://github.com/CocoaPods/trunk.cocoapods.org/issues/172#issuecomment-204812526

**Comment by ricardopereira** [comment]
It's already [done](https://github.com/ably/ably-ios/commit/c68bcb60e9c05210b410259934585e7d971c9232#diff-9c8b42a779d2522373a1a6a9e3846dafR22).
Can we close this?

**Comment by mattheworiordan** [comment]
I think so. @tcard you happy?

**Comment by tcard** [comment]
Yes.
