### ISSUE TITLE
Update installation guide when Ably 0.8 podspec is live

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#294]
- [x] https://github.com/ably/docs/search?utf8=%E2%9C%93&q=pod
 - [x] https://github.com/ably/ably-ios/blob/master/README.md

**Comment by mattheworiordan** [comment]
I believe this is done, see https://github.com/ably/docs/commit/5ca856c08532da90f301cdc7d6f75c9a7ade7b30.

@ricardopereira @tcard please confirm and close this if so
