### ISSUE TITLE
Add support for Swift 2.2

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#345]
_Xcode 7.3 includes Swift 2.2 and SDKs for iOS 9.3..._

**Comment by ricardopereira** [comment]
This is important right now. The Xcode 7.3 is already on the AppStore. It won't be possible to use it if someone want to try out the latest client version. Swift syntax has changed but we can use different versions on the code. Swift 2.2 introduces a new compiler directive that makes cross-version compatibility. It is a compile time feature:

```
#if swift(>=3.0)
print("Running Swift 3.0 or later")
#else
print("Running Swift 2.2 or earlier")
#endif
```

**Comment by tcard** [comment]
Sorry @ricardopereira, are you saying that the library right now doesn't work with Swift 2.2?

**Comment by ricardopereira** [comment]
Yes because we are using the SwiftWebSocket. I think we only need to update the dependency because CocoaPods will only install the dependency and select the ObjC code of the client. We can update the `Spec` to Swift 2.2 later.

**Comment by ricardopereira** [comment]
I'm downloading the Xcode 7.3 and I will test it.
