### ISSUE TITLE
Realtime: there is no dedicated object to manage connections

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#36]

**Comment by mattheworiordan** [comment]
Ok, this in itself is not necessarily an issue, however are you therefore implying that all of `RTN*` cannot be supported, without a refactor i.e. we need a `Connection` object, but whether it is managed with a `ConnectionManager` or a state machine for example, is not necessarily part of the spec.

**Comment by ricardopereira** [comment]
@mattheworiordan There is no Connection object either. The Realtime client instances a Transport object and connects to the server with the current WebSocket. Just one connection per client.

**Comment by mattheworiordan** [comment]
@ricardopereira that is fine, other than the `ably-js` library, there is only ever one transport open using WebSockets, and in all libraries there is only ever one `Connection` open as well. As a workaround, we could perhaps simple create a Proxy Connection object that exhibits the properties described in the spec, but simply references the attributes in the Client itself. That way, we don't need to refactor now, and can easily do it later without changing the interface.  WDYT?

**Comment by ricardopereira** [comment]
Well, the connection is handled on the `ARTWebSocketTransport`. I can add a protocol to mirror the existing methods from `ARTRealtime`. Like you said, a proxy Connection object. It's the best workaround.

**Comment by mattheworiordan** [comment]
BTW. What happens when the transport is closed & re-opened (such as connection failure), does the `ARTWebSocketTransport` remain consistent or is a new object created each time?

**Comment by ricardopereira** [comment]
The object remains consistent.

**Comment by mattheworiordan** [comment]
Ok, great, well lets go with a proxy object for now as that will allow us to meet the requirements of the spec easily

**Comment by ricardopereira** [comment]
https://github.com/ably/ably-ios/blob/2398b9580d6aaef45ca91c01a99160cf09bbd4d9/Source/ARTConnection.h#L19
