### ISSUE TITLE
Realtime: timeouts implementations are outdated

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#41]
I'm opening this issue because of:

```
(RTC7) The client library must use the configured timeouts specified in the ClientOptions, 
falling back to the client library defaults and defaults described in ClientOptions below
```

Currently, the `ClientOptions` doesn't have any of the `TO3l` specifications:
- **disconnectedRetryTimeout**: possible to implement with small refactoring
- **suspendedRetryTimeout**: possible to implement with small refactoring
- **httpOpenTimeout**: bigger refactoring
- **httpRequestTimeout**: bigger refactoring
- **httpMaxRetryCount**: bigger refactoring
- **httpMaxRetryDuration**: bigger refactoring

The Realtime client use some defaults (basic timeouts):
- **connectTimeout**: on connecting to the server
- **disconnectTimeout**: retry interval when Disconnected
- **suspendTimeout**: retry interval when Suspended

Different from what's defined on [DF1](http://docs.ably.io/client-lib-development-guide/features/#defaults).

`DF1a` and `DF1b` requires some refactoring.

**Comment by ricardopereira** [comment]
With this I need to now what's important to test right now having in mind the current state of the lib.

@mattheworiordan /cc @paddybyers

**Comment by ricardopereira** [comment]
Check changes:
https://github.com/ably/docs/commit/1f853e96b1a63fadf9c7c9f613d1a1d273a048cd

**Comment by mattheworiordan** [comment]
@ricardopereira implementing configurable timeouts is probably lower priority for now.

I am not sure what you mean by `DF1a` and `DF1b` needing refactoring, to be clear the impact I assume is:

* `connectionStateTtl ` will simply map the existing max time in state for the disconnected state i.e. the iOS Realtime library should have already implemented some mechanism to move from the `disconnected` state to the `suspended` state after X time after being `disconnected`.  `connectionStateTtl` is simply this value.  Either way, this is not a public API attribute anyway
* `realtimeRequestTimeout` is simply a generic timeout value that is applied to any request that should auto-fail if a response does not come back in that time, for example `(RTN12b) If the CLOSED ProtocolMessage is not received within the default realtime request timeout, the transport will be disconnected and the connection will automatically move to the CLOSED state`

**Comment by tcard** [comment]
This is done.
