### ISSUE TITLE
Add reauth capability

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#452]
See https://github.com/ably/docs/pull/113 for the spec, and https://github.com/ably/ably-js/pull/269 for the JS implementation.  We need to implement this in this library soon.

**Comment by ricardopereira** [comment]
RSA8e: #487
RSA9h: #494
RSA10j: #492
RSA10d: #493
RSA10k: #495
RSA10g: #494
RTC8: https://github.com/ably/ably-ios/commit/a157ad6d78fdcfd849844e4e7f3cb4b715c41be6#diff-b5d84fe9bce26902a7481c2ffec84fffR1907
TK2d: #508
