### ISSUE TITLE
Environment option is "production"

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#511]
If environment option is configured and is "production" then use the default hosts. Part of http://docs.ably.io/client-lib-development-guide/features/#RSC11.

**Comment by tcard** [comment]
It's not "use the default hosts" but "don't prepend the environment (ie. `production-`) to the hosts", custom or not. `environment="sandbox",restHost="fake.ably.io"` should send requests to `sandbox-fake.ably.io`, while `environment="production",restHost="fake.ably.io"` should send them to `fake.ably.io`.
