### ISSUE TITLE
Wrong message timestamp on 32-bit devices

### ISSUE THREAD

**Issue by disabled** [ably/ably-ios#525]
Hello, 

We are using ably-php to send messages and ably-ios to receive them.
In this scenario, message timestamp on iOS is wrong (using either ARTRest or ARTRealtime), but only on 32-bit devices. On 64-bit devices everything is working fine.

Here is example:
```
(lldb) po message
<ARTMessage: 0x7a947140> {
 id: QT69HcQfip:0:0,
 clientId: (null),
 connectionId: (null),
 timestamp: 1969-12-23 02:33:04 +0000,
 encoding: (null),
 data: { ... },
 name: message
}

po [message.timestamp timeIntervalSince1970]
-768415.03600001335

```

**Comment by mattheworiordan** [comment]
Hi @disabled.  Nice Github handle :)

@ricardopereira @tcard can you please advise on this issue?

**Comment by tcard** [comment]
Hi @disabled! Thanks for the report. I've just pushed a fix to the repo. It will be included in the next release. In the meantime, you can point your Podfile (or however you're including the library) to the current master branch head.

Please tell us if this actually fixes your problem, and of any other problem you may encounter. Thanks in advance!

**Comment by disabled** [comment]
Hi @tcard. Thanks, timestamp is working fine now!
