### ISSUE TITLE
Token Request 'ttl' should be in milliseconds

### ISSUE THREAD

**Issue by aquigriffin** [ably/ably-ios#529]
Please represent 'ttl' property of ARTTokenRequest in milliseconds to maintain consistency with other client libraries.  For instance, our servers use the Ably-Java lib 0.8.5, to return a token request during the authCallback in the iOS client.  The java lib respects the 'ttl' as milliseconds, but the iOS client uses seconds.

**Comment by mattheworiordan** [comment]
@aquigriffin we have this one scheduled to be fixed along with adding some new functionality to make the handling of `TokenRequest` or `TokenDetails` serialised JSON objects easier, see https://github.com/ably/docs/pull/193.
