### ISSUE TITLE
PagiantedResult isLast and hasNext are methods, not attributes

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#534]
See https://github.com/ably/docs/issues/185

We should bundle this breaking change into 0.9

**Comment by tcard** [comment]
Sadly the train has left on this one.

Personally I don't think this is bad enough to grant a breaking change, even on a major release. I've mentioned before that the spec should allow fields to be implemented as 0-ary methods and vice versa, in accordance to the Uniform Access Principle.

**Comment by mattheworiordan** [comment]
> Sadly the train has left on this one.

Agreed. 🚂
