### ISSUE TITLE
0.9 spec: Extras field

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ios#552]
ably/docs#203

**Comment by mattheworiordan** [comment]
@tcard  is this not implemented already?  Can we close this issue?

**Comment by tcard** [comment]
No, suprisingly it isn't, neither in master nor in the push branch. I'll do it now.

**Comment by mattheworiordan** [comment]
> nor in the push branch

If it's not in the push branch, how could push even work from the library itself?  I assume it didn't right?

**Comment by tcard** [comment]
If you mean how could you send push notifications from the library, you could use `rest.push.publish`, but yes, it had incomplete support. I'm not sure how we overlooked this...
