### ISSUE TITLE
Library crash bug reports

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ios#553]
Bug reports from a customer:
1. '*library crashes if you try to publish with a Dictionary instead of an NSDictionary. However, the library accepts "Any", so you would kind of assume that it can take anything*'
2. '*library crashed when I didn't convert an enum to its rawValue (I feel like this can be converted automatically, but I may be wrong). There was no error given back, nor a catchable exception - it instead threw an exception up to the top.*'

**Comment by ricardopereira** [comment]
@SimonWoolf Which Swift version? v2.2, v2.3 or v3.0?

**Comment by danielrhodes** [comment]
Hi @ricardopereira, I was the one who had these issues. Using 3.0.

**Comment by ricardopereira** [comment]
Thank you @danielrhodes. I will look into it and let you know when it's fixed.

**Comment by danielrhodes** [comment]
Great. Let me know how I can help.

**Comment by ricardopereira** [comment]
@danielrhodes 

1. I tried to reproduce it like:

```
rest = ARTRest(key: "<redacted>")
let data: Dictionary = ["foo":1]
rest.channels.get("ios").publish(nil, data: data) { error in
    print(error) //no error, no crash
}
```

but no crash or error.
**Xcode Version 8.1 (8B62) (Swift 3.0)**

2. Which enum for example?

Maybe it's better if could you add a short runnable sample to reproduce those issues, please.

**Comment by danielrhodes** [comment]
First of all, I was using `ARTRealtime`, it that makes a difference.

Let me get back to you on the `Dictionary` stuff. I think ultimately it was the enum that was causing issues.

The enum was something like this:

```swift
enum MessageType: Int {
  case unknown = 0
  case message = 1
  case receipt = 2
  case action = 3
  case room = 4

  var isError: Bool {
    return self == .unknown
  }
}
```

**Comment by ricardopereira** [comment]
@danielrhodes Which error occurs? Is it an **`uncaught exception 'NSInvalidArgumentException': must be NSString, NSData, NSArray or NSDictionary.`**?

How do you publish the message?
 - `publish(nil, data: MessageType.message.rawValue)`
 - `publish(nil, data: MessageType.message)`

@tcard Should we support any type while publishing a message (whether it is a class, enum, struct, or any other Swift type)?

**Comment by tcard** [comment]
@ricardopereira No, we shouldn't. The spec [says](http://docs.ably.io/client-lib-development-guide/features/#RSL4a): "Payloads must be binary, strings, or objects capable of JSON representation, or can be empty (omitted). Any other data type should not be permitted and result in an error" That's NSData, NSString, NSDictionary of JSON-encodable objects, NSArray of JSON-encodable objects and nil. Any other type must be encoded to those types first, including enums.

**Comment by ricardopereira** [comment]
@tcard Thanks.
@danielrhodes I think your best choice is to publish the `MessageType` as a NSNumber like: **`publish(nil, data: MessageType.message.rawValue as NSNumber)`**. You can cast it directly because Swift does the conversion automatically if the enum is a `RawRepresentable` of type Int, Float, and so on (basically numeric types).

**Comment by tcard** [comment]
@ricardopereira @danielrhodes Sorry but no, NSNumber is not one of the supported types. They should be serialized e. g. to NSString first.

**Comment by SimonWoolf** [comment]
@tcard 

> The spec says: "Payloads must be binary, strings, or objects capable of JSON representation, or can be empty (omitted). Any other data type should not be permitted and result in an error" That's NSData, NSString, NSDictionary of JSON-encodable objects, NSArray of JSON-encodable objects and nil

> Sorry but no, NSNumber is not one of the supported types.

Sorry to butt-in when I'm not an ios dev, but -- why not? Numbers (and booleans) are JSON-encodable objects, and a lone (stringified) number is a valid json text - https://tools.ietf.org/html/rfc7159#section-2 .
