### ISSUE TITLE
Feedback from customer re private methods

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ios#554]
Feedback from a customer that: "*there are lots of undocumented functions (which ones can I safely use? Nothing is private.*". Matt mentioned they need to send messages to each other; customer replied that that "*has been solved with Objective-C using private headers, and it has been solved in Swift with "internal" and "fileprivate" attribute on functions/classes.*"

**Comment by tcard** [comment]
We do keep separate public and private headers. I'm not sure how the customer get access to the private headers. From a fresh Xcode project and installing Ably normally I can only see the public API.

**Comment by ricardopereira** [comment]
Yes, we keep it separated but maybe the customer is adding the lib manually. @SimonWoolf Can you confirm that is the case?

**Comment by ricardopereira** [comment]
<img width="489" alt="screen shot 2016-12-07 at 13 56 10" src="https://cloud.githubusercontent.com/assets/3541185/20970328/f3e4509e-bc84-11e6-91c8-745439058ecb.png">

Showing only what's public.

**Comment by danielrhodes** [comment]
![screen shot 2016-12-08 at 13 31 55](https://cloud.githubusercontent.com/assets/120044/21028619/dd3ec736-bd4a-11e6-9928-72b9aaf2d318.png)

![screen shot 2016-12-08 at 13 35 48](https://cloud.githubusercontent.com/assets/120044/21028725/4be0806c-bd4b-11e6-814e-e95aebd02187.png)

I'm not sure if any of these are supposed to be private, but some of them don't seem to be listed on your documentation.

**Comment by tcard** [comment]
@danielrhodes Thanks. All of those are correctly public. ARTRealtimeChannel is described [here](https://www.ably.io/documentation/realtime/channels-messages#properties) (make sure you select Swift at the top-right) and ARTRealtimeChannels isn't really in the documentation proper but it is in [our thorough API spec](http://docs.ably.io/client-lib-development-guide/features/#RSN1) that all our client libraries implement.

We really could do a better job mapping in-library documentation to the docs, though! So thanks for bringing this into our attention. We'll definitely work to improve this.

**Comment by tcard** [comment]
Closing as we're tracking this issue specifically somewhere else now.
