### ISSUE TITLE
Should Emphasize That ARTRealtime Needs To Be Created On Main Queue

### ISSUE THREAD

**Issue by sikhapol** [ably/ably-ios#577]
I was stuck with this frustrating issue yesterday when I tried to create `ARTRealtime` in the callback from `URLSessionTask` and never get it to work. After many hours I tried wrapping the initialization code in `DispatchQueue.main.async { ... }` and, surprisingly, everything start to work again.

So try digging in the documentation on Ably website, to find if it's mentioned anywhere that `ARTRealtime` is needed to be created on main thread but didn't find any.

So I think it's worth considering putting this information in the documentation somewhere.

**Comment by ricardopereira** [comment]
@sikhapol Creating a realtime object in a background queue should be a valid behaviour. This should be fixed. Thanks for reaching out.
/cc @mattheworiordan

**Comment by mattheworiordan** [comment]
Thanks @sikhapol and sorry for the inconvenience. @ricardopereira do you know what to do then?

**Comment by ricardopereira** [comment]
@sikhapol There is a PR available fixing this particular issue. You can test it by using `pod 'Ably', :git => 'https://github.com/ably/ably-ios.git', :branch => 'fix-577'`. Thanks again.

Code I used to test it:
```
    var realtime: ARTRealtime!
    var rest: ARTRest!

    override func viewDidLoad() {
        super.viewDidLoad()
        URLSession.shared.dataTask(with: URL(string: "https://github.com")!) { data, response, error in
            self.work()
        }.resume()
    }

    func work() {
        let options = ARTClientOptions(key: <redacted>)
        options.autoConnect = false
        options.logLevel = .verbose
        self.realtime = ARTRealtime(options: options)
        self.realtime.connect()
        self.realtime.ping { error in
            print("REALTIME", error ?? "no error")
        }
        self.realtime.channels.get("foo").attach() { error in
            print("REALTIME", error ?? "no error")
        }

        self.rest = ARTRest(options: options)
        self.rest.channels.get("foo").presence.get { members, error in
            print("REST", error ?? "no members")
            print("REST", error ?? "no error")
        }
    }
```

**Comment by sikhapol** [comment]
@mattheworiordan @ricardopereira Sorry, I just saw this. Thank you guys very much for your prompt response and for working on this. Keep up the good work 👍
