### ISSUE TITLE
Calling enter() on an unidentified client should error

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ios#579]
[RTP8f](http://docs.ably.io/client-lib-development-guide/features/#RTP8f): "If the client library is authenticated but unidentified (i.e. clientId is a wildcard '*' or client is anonymous), the enter request results in an error immediately"

Customer [here](https://app.intercom.io/a/apps/ua39m1ld/inbox/all/conversations/7834795990) was calling enter() on an unidentified client, and didn't get an error

**Comment by SimonWoolf** [comment]
(Note that if the ios lib were just sending it off with no clientid, realtime would respond with a `{"message":"Malformed message; no clientId in message or inferred from connection","code":40012,"statusCode":400}` NACK, which should be exposed in the error attr of the callback. Apparently that didn't happen either, so not sure what was going on)

**Comment by ricardopereira** [comment]
@SimonWoolf I don't have access to Intercom but it's weird that the client didn't get an error because the spec is working.

```
// RTP8f
it("should result in an error immediately if the client is anonymous") {
    let client = ARTRealtime(options: AblyTests.commonAppSetup())
    defer { client.dispose(); client.close() }
    let channel = client.channels.get("test")

    waitUntil(timeout: testTimeout) { done in
        channel.presence.enter(nil) { error in
            expect(error!.message).to(contain("attempted to publish presence message without clientId"))
            done()
        }
    }
}
```

**Comment by mattheworiordan** [comment]
@ricardopereira I've asked the customer to comment in this issue.

**Comment by funkyboy** [comment]
@SimonWoolf @mattheworiordan do you think we can close this?

**Comment by mattheworiordan** [comment]
Sure, close it given the customer has not responded and we have no reason to believe it does not work
