### ISSUE TITLE
Presence message timestamp interpretation is wrong

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ios#580]
Presence message received by an objective-c client:
```
<ARTPresenceMessage: 0x15e9a450> {
id: GH-MFD4bT3:0:0,
clientId: <redacted>,
connectionId: GH-MFD4bT3,
timestamp: 1969-12-17 17:35:16 +0000,
encoding: (null),
data: <redacted>,
action: 2
}
```
Note the timestamp, which is around a million seconds *before* the epoch. Not sure how that happens

**Comment by ricardopereira** [comment]
@SimonWoolf Which client version? I think this was fixed. Please see https://github.com/ably/ably-ios/issues/525.

**Comment by ricardopereira** [comment]
This issue has been closed due inactivity.
