### ISSUE TITLE
Check 1.0 docs for accuracy against 0.9 changes

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#581]
See https://github.com/ably/docs/issues/264 and 1.0 PR at https://github.com/ably/docs/pull/260

@ricardopereira please can you do a similar task to what Peter did and review all Realtime & REST API docs and provide a list of what needs changing please.

Please note that Peter did not provide a list of links to Github as a reference for method definitions / interfaces etc.  Please can you do that so that it's easier for me to jump straight to code when working out what to change.

**Comment by ricardopereira** [comment]
https://github.com/ably/docs/blame/77fe470b34d29524a4ed1e118e83d2f649e2ce33/content/root/quick-start-guide.textile#L142
(only the Blame view provides the ability to link to a specific line within the source)

Use `ARTRealtimeConnectionEvent` instead of `ARTRealtimeConnectionState`.

```
[realtime.connection once:ARTRealtimeConnectionEventConnected callback:^(ARTConnectionStateChange *stateChange) {
```

**Comment by ricardopereira** [comment]
# Types

## ARTTokenRequest

`ttl` property of type `NSTimeInterval` in Swift & ObjC:
https://github.com/ably/docs/blame/77fe470b34d29524a4ed1e118e83d2f649e2ce33/content/types/_token_request.textile#L9

`timestamp` property of type `NSDate` in Swift & ObjC:
https://github.com/ably/docs/blame/77fe470b34d29524a4ed1e118e83d2f649e2ce33/content/types/_token_request.textile#L10

**Comment by ricardopereira** [comment]
Done ✅

**Comment by mattheworiordan** [comment]
Thanks, please leave this open as we need to update this before we release 1.0.

**Comment by mattheworiordan** [comment]
@ricardopereira I believe this is all fixed in	155fa73. I'm merging into www.ably.io/documentation now so it would be nice if you could double check the issues you mentioned above and confirm everything is OK. Thanks

**Comment by ricardopereira** [comment]
@mattheworiordan Reviewed. I only found this issue https://github.com/ably/docs/pull/285.

**Comment by mattheworiordan** [comment]
Thanks @ricardopereira
