### ISSUE TITLE
Cannot install via Cocoapods with Xcode 7.3.1

### ISSUE THREAD

**Issue by derrickhunt** [ably/ably-ios#587]
I am currently running Xcode version 7.3.1 and cannot install Ably via Cocoapods.

I am seeing the following error:
[!] Unable to find a specification for `Ably (~> 0.8)`

I have other pods in my podfile that work fine when the Ably pod is commented out, so I am pretty sure this an issue with Ably and not Cocoapods. I am on the latest version of Cocoapods.

**Comment by ricardopereira** [comment]
@derrickhunt Could you run **`pod repo update`** and try again please?

**Comment by derrickhunt** [comment]
@ricardopereira That did the trick! I was unaware of that change, thanks for the heads up.
