### ISSUE TITLE
Crash in ARTJsonLikeEncoder

### ISSUE THREAD

**Issue by matt-OfferUp** [ably/ably-ios#589]
Our iOS client has been crashing because of the Ably SDK (0.8.8). In the protocolMessageFromDictionary method in ARTJsonLikeEncoder, if an error is received, an ARTErrorInfo is being created. When this happens, if [error artString:@"message"] returns nil the app will crash. This has happened to us quite a bit in the last 24 hours.
I also updated the app to use version 1.0.0 (for my testing) but this still appears to be an issue.

**Comment by ricardopereira** [comment]
@matt-OfferUp Sorry for the inconvenience. It was easy to reproduce the issue from your description, thanks. Can you test the fix by using `pod 'Ably', :git => 'https://github.com/ably/ably-ios.git', :branch => 'fix-589'`? Thanks again.

**Comment by matt-OfferUp** [comment]
This looks like it will work. I dont have a way to force this to happen so I am just looking at the code but this should fix the crash.

**Comment by ricardopereira** [comment]
Updates released:
 - [v1.0.1](https://github.com/ably/ably-ios/releases/tag/1.0.1)
 - [v0.8.11](https://github.com/ably/ably-ios/releases/tag/0.8.11)

**Comment by mattheworiordan** [comment]
Ok, thanks
