### ISSUE TITLE
Push: uncaught exception

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#594]
Customer (Edgar) reported this issue

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[.../Pods/Ably/Source/ARTPushActivationState.m:38 -[ARTPushActivationState transition:]] should always be overriden.'
```

**Comment by ricardopereira** [comment]
@mattheworiordan Could Edgar test the `push-spec-activationstatemachine` branch and see if it works?

**Comment by itolisto** [comment]
Hi @ricardopereira, effectively, branch `push-spec-activationstatemachine` is working
