### ISSUE TITLE
Crash strategy

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#596]
@ricardopereira @tcard as discussed, we are going to approach the reported crashes in the library in four ways:

* [x] Wrap all public methods with error handling such that an error is handled, logged, and the connection is moved to the failed state (if appropriate).  The same generic handler should also apply to any incoming events that generate exceptions, and I expect in almost all cases should move the connection to the failed state.
* [x] Like a lot of more traditional lower level libraries, they often make assertions about state/properties/context before executing code.  Whilst this won't add any more resilience to the code i.e. it will still fail, it will hopefully help us to diagnose issues more quickly as we can add more context to the failure i.e. a field was expected, an non-null value was expected, and include other details.
* [x] The logger should store the last X log lines at verbose level (we need to think about the implications of this from a performance perspective though, can we cache the log entries but perhaps not interpolate the log line until needed?) so that when we generate error reports, we have more context to the events leading up to this crash.
* [x] We will consider how we can introduce an Ably client-library exception reporting service where we can send errors when an unexpected error in the library occurs.

PS. Can we double check that https://docs.ably.io/client-lib-development-guide/features/#RTE6 is working.  I am not sure we would need to log these errors to the central service as these are errors in customer code, not ours.  However, we should definitely output that to the local logger and handle the error gracefully.

**Comment by tcard** [comment]
All done.
