### ISSUE TITLE
Document thread-safety requirements in current version

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#601]
We need to document that the iOS lib is not thread-safe and thus we need to:

* [x] Add documentation in [realtime usage section](https://www.ably.io/documentation/realtime/usage) stating that the iOS lib is not thread-safe, with a high level summary of the types of problems they can expect, a recommendation and link to [how Apple recommends they deal with concurrency](https://developer.apple.com/library/content/documentation/General/Conceptual/ConcurrencyProgrammingGuide/ConcurrencyandApplicationDesign/ConcurrencyandApplicationDesign.html#//apple_ref/doc/uid/TP40008091-CH100-SW1) and provide a very simple example of how to address this using for example GCD sync dispatch.
* [x] Add the above notes to Github
* [x] Add info about the objects we pass in listeners and notes on their safety to use in that we don't keep references to them.

**Comment by tcard** [comment]
See 0e48e63.

**Comment by mattheworiordan** [comment]
@tcard 0e48e63 is not a commit?

**Comment by tcard** [comment]
@mattheworiordan Sorry, it's a commit on docs: https://github.com/ably/docs/commit/0e48e636a9e9036f6250350e0bad2e46c2445feb

**Comment by tcard** [comment]
BTW, as part of #603 I put state transitions in GCD serial queues, which should reduce thread-safety issues and possibly even make the library internally thread-safe.

**Comment by paddybyers** [comment]
> and possibly even make the library internally thread-safe

You don't sound very sure?

**Comment by tcard** [comment]
@paddybyers It definitely improves the situation, I'm not sure if it makes it _completely_ thread-safe internally.

**Comment by mattheworiordan** [comment]
> You don't sound very sure?

@paddybyers remember we still have [our spike](https://github.com/ably/ably-ios/issues/602) to complete

**Comment by tcard** [comment]
Done.
