### ISSUE TITLE
Spike: Review what's needed to use GCD to make the lib thread-safe

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#602]
See what's involved in making the lib thread-safe with GCD.

Need to work out what changes need to be made:

* [ ] State changes
* [ ] Registering listeners
* [ ] Publishing / presence changes
* [ ] Subscribing and Emitting efficiently

Then we can establish if there are any internal implications too that need fixing ASAP.

**Comment by mattheworiordan** [comment]
BTW. I believe there is no need to add thread-safety to v0.8.

**Comment by tcard** [comment]
This has been implemented in #620.
