### ISSUE TITLE
ARTPush didRegisterForRemoteNotificationsWithDeviceToken error

### ISSUE THREAD

**Issue by itolisto** [ably/ably-ios#611]
Hi,

I'm getting an error when calling 

`[ARTPush didRegisterForRemoteNotificationsWithDeviceToken:deviceToken realtime:ably];`

<img width="1440" alt="screen shot 2017-06-06 at 22 14 13" src="https://user-images.githubusercontent.com/11670462/26862150-3771811e-4b06-11e7-9c59-cf1fa0902c38.png">

My podfile:

```
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

# Used when using Swift libraries in a Objective-C project
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target 'Conversa' do
    pod 'Ably', :git => 'https://github.com/ably/ably-ios.git', :branch => 'push'
end
```

But if I use the branch 'push-spec-activationstatemachine' when I call the method

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    ARTRealtime *ably = [[CustomAblyRealtime sharedInstance] getAblyRealtime];
    if (ably) {
        [ARTPush didRegisterForRemoteNotificationsWithDeviceToken:deviceToken rest:ably.rest];
    }
}
```

Nothing seems to happen.

**Comment by ricardopereira** [comment]
@itolisto Could you test the `push-spec-activationstatemachine` branch and see if it works please?

`pod 'Ably', :git => 'https://github.com/ably/ably-ios.git', :branch => 'push-spec-activationstatemachine'`

**Comment by tcard** [comment]
@ricardopereira Is there anything blocking merging that with `push`?

**Comment by ricardopereira** [comment]
@tcard No, it's good.

**Comment by itolisto** [comment]
@ricardopereira Branch `push-spec-activationstatemachine` is working. Just have a question, when `[ARTPush didRegisterForRemoteNotificationsWithDeviceToken:deviceToken rest:ably.rest]` is called is has to print to console the device token right? But I can't see the "ARTPush: device token received" message in the logs.

**Comment by tcard** [comment]
@itolisto Does it work if you print the `deviceToken` yourself? If not, there's something wrong about your push setup, since that part doesn't depend on Ably. Did you follow through [Apple's documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1)?

**Comment by itolisto** [comment]
@tcard Yes, I'm receiving the `deviceToken` that's precisely why I don't understand why push notifications aren't working. 

As I mentioned when I submitted the issue (and if you look closely to the image attached) when I use the `push` branch the `deviceToken` is printed in console and when the `didRegisterForRemoteNotificationsWithDeviceToken` method is called the app crashes. On the other hand, if I use the `push-spec-activationstatemachine` branch, the token is not printed in console but the app doesn't crash.

Any ideas?
