### ISSUE TITLE
Connection resume failure detaches all channels

### ISSUE THREAD

**Issue by tcard** [ably/ably-ios#612]
From https://support.ably.io/helpdesk/tickets/1915:

> “I’ve been hitting occasional errors which say this "2017-06-06 15:16:02.768 Thred[48904:32755281] WARN: R:0x618000196e70 ARTRealtime: connection has reconnected, but resume failed. Detaching all channels”
>
>According to their docs when you lose connection it should reconnect and re-attach to any channels you’re subscribed to, so why this error is occurring I’m not sure.  I haven’t been able to consistently repro it either so I’m honestly not sure why its happening.”

So I've checked the code and: when after a resume attempt (which happens [if CONNECTING after FAILED, DISCONNECTED and SUSPENDED](https://github.com/ably/ably-ios/blob/a0dbdddcde74b53ff4b8cfcb6417490ca3c622af/Source/ARTRealtime.m#L378-L383)) the received connection ID is a new one, then [we detach all channels](https://github.com/ably/ably-ios/blob/a0dbdddcde74b53ff4b8cfcb6417490ca3c622af/Source/ARTRealtime.m#L556-L562).

At this point, in theory, the channel [got suspended](https://github.com/ably/ably-ios/blob/a0dbdddcde74b53ff4b8cfcb6417490ca3c622af/Source/ARTRealtime.m#L515-L517), so after the detach above [the channel will reattach](https://github.com/ably/ably-ios/blob/a0dbdddcde74b53ff4b8cfcb6417490ca3c622af/Source/ARTRealtime.m#L496-L500) as expected, and the reported log message is just misleading. But if the channel wasn't suspended, e. g. because the library was in the DISCONNECTED state (and thus the channels were still ATTACHED) while the server already forgot its connection state, then nothing will happen and the channels won't reattach.

I think that corner case should be explicitly added to the spec, something like "if, after a CONNECTED message is received when trying to resume, the new connection ID doesn't match the previous one, act as if the connection transitioned from SUSPENDED to CONNECTING to CONNECTED".

**Comment by mattheworiordan** [comment]
> I think that corner case should be explicitly added to the spec, something like "if, after a CONNECTED message is received when trying to resume, the new connection ID doesn't match the previous one, act as if the connection transitioned from SUSPENDED to CONNECTING to CONNECTED".

@tcard sure, that makes sense to me. @paddybyers @SimonWoolf do you agree?

**Comment by SimonWoolf** [comment]
> But if the channel wasn't suspended, e. g. because the library was in the DISCONNECTED state (and thus the channels were still ATTACHED) while the server already forgot its connection state, then nothing will happen and the channels won't reattach.

Why isn't that already covered by [RTN15c3](https://docs.ably.io/client-lib-development-guide/features/#RTN15c3)? "*... a CONNECTED ProtocolMessage with a new connectionId ... For all channels in the ATTACHING or ATTACHED state, the client library should fail any previously queued messages for that channel and initiate a new attach ...*"

**Comment by tcard** [comment]
By the way, the course of action for iOS in my opinion should be to remove [these lines](https://github.com/ably/ably-ios/blob/a0dbdddcde74b53ff4b8cfcb6417490ca3c622af/Source/ARTRealtime.m#L556-L562) and instead do something like "for all channels: if channel is attached: move to suspended". Then, the channel [will reattach](https://github.com/ably/ably-ios/blob/a0dbdddcde74b53ff4b8cfcb6417490ca3c622af/Source/ARTRealtime.m#L496-L500) as expected.

**Comment by tcard** [comment]
@SimonWoolf True, I didn't see that. Arguably that should be under/referenced from [connection state change side effects for channels](https://docs.ably.io/client-lib-development-guide/features/#RTL3).

**Comment by tcard** [comment]
[This is the test for RTN15c3](https://github.com/ably/ably-ios/blob/a0dbdddcde74b53ff4b8cfcb6417490ca3c622af/Spec/RealtimeClientConnection.swift#L2393-L2394). It doesn't look right to me, it checks that the channel ends up detached while RTN15c3 says "The client library should initiate an attach for channels that are in the SUSPENDED state. For all channels in the ATTACHING or ATTACHED state, the client library should fail any previously queued messages for that channel and initiate a new attach i.e. a new ATTACH ProtocolMessage must be sent for each channel".

**Comment by SimonWoolf** [comment]
> This is the test for RTN15c3. It doesn't look right to me, it checks that the channel ends up detached

Yep, looks like that's a test for the 0.8 version of RTN15c3, it got rewritten for 1.0 as part of the auto-channel-reattach changes. 

>  the course of action for iOS in my opinion should be to remove these lines and instead do something like "for all channels: if channel is attached: move to suspended".

I disagree, that'd be an out-of-spec use of `suspended` (the user would get a state change to `suspended`, then immediately after one for `attaching`). (We did actually discuss doing that as a way to signal a channel discontinuity to the user when planning 1.0, but rejected it in favour of the `resumed` flag, see discussion https://github.com/ably/wiki/issues/106 ). Correct behaviour is to just initiate a reattach, so channels go from `ATTACHED` straight to `ATTACHING`, see eg https://github.com/ably/ably-js/blob/master/common/lib/transport/connectionmanager.js#L659-L669

**Comment by ricardopereira** [comment]
PR is open with the fix ^
