### ISSUE TITLE
Memory leak when publishing via realtime

### ISSUE THREAD

**Issue by tcard** [ably/ably-ios#625]
See screencast: https://www.screencast.com/t/IE5uVcUj

The user bisected this as a regression from 1.0.3 to 1.0.4, when Sentry was introduced.

**Comment by tcard** [comment]
I can't reproduce this. I've used this code:

```swift
func publish() {
    let channel = client.channels.get("test")
    channel.publish("event", data: "ASDFASDLPFG,ASDKLPFGMPASDKMFPKOASKMDFPIOADSPIFJ OIMADSOIFCMOIASJDFPIOAMSÒIFPCOIAWJERPMOICJAWEPOCMPEOIRJCMPAOIWECFRPOAIWEJFCPMOIAWEJFMCPOAWIJEFPOCMIOPJAMWIOEFJCMPOAIWEJFPCMO ASDOFKAI,ACSIOEJRSAPOF")
    delay(0.2) {
        publish()
    }
}
```

But the memory kept constant the whole time...

**Comment by ricardopereira** [comment]
@tcard Please ask the user to try this branch and see if it helps: `pod 'Ably', :git => 'https://github.com/ably/ably-ios.git', :branch => 'fix-625'`. I turned off the additional log data for Sentry.

**Comment by ricardopereira** [comment]
Enabling address sanitizer could also help us getting more information: https://developer.apple.com/documentation/code_diagnostics/address_sanitizer/enabling_the_address_sanitizer

The client should enable it and look something like ⬇️ in the log:

```
==7829==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x42c0c5 in __interceptor_malloc /usr/home/hacker/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:74
    #1 0x43ef81 in main /usr/home/hacker/memory-leak.c:6
    #2 0x7fef044b876c in __libc_start_main /build/buildd/eglibc-2.15/csu/libc-start.c:226

SUMMARY: AddressSanitizer: 7 byte(s) leaked in 1 allocation(s).
```

**Comment by ricardopereira** [comment]
Nevermind. I reproduce it successfully 🙌

**Comment by ricardopereira** [comment]
Code to reproduce the problem:

```
// Using Ably version 1.0.7

import UIKit
import Ably

class ViewController: UIViewController {

    @IBOutlet weak var button: UIButton!

    let options = ARTClientOptions(key: "<redacted>")
    var realtime: ARTRealtime!

    override func viewDidLoad() {
        super.viewDidLoad()
        button.addTarget(self, action: #selector(self.didTouchButton), for: .touchUpInside)

        options.logLevel = .debug
        realtime = ARTRealtime(options: options)
        let channel = realtime.channels.get("memory-leak")
	channel.attach()
    }

    func didTouchButton() {
        let channel = realtime.channels.get("memory-leak")
        var i = 0
        while i != 10000000 {
            channel.publish(nil, data: "asdlçfjaslçdkjf aslkjd alskdjf")
            i += 1
        }
    }

}
```

**Comment by tcard** [comment]
@ricardopereira Hmm, I think that will put 10000000 messages in the "waiting for ACK" queue right away, but that's not a leak, that's expected. That's why I put a delay in my code between iterations,  to give some room for ACKs to arrive. The user said he was publishing at a 2 messages/sec rate. Are you sure that's not it?

**Comment by ricardopereira** [comment]
I’ll check that but it makes sense what you said. Thanks.

**Comment by mattheworiordan** [comment]
FYI, customer stated in regards to the env:

> We are sending messages through Ably very rapidly, about once every 100ms. I was running on device, not simulator, but I was using a Debug configuration. This is a React Native project, and are also using Twilio Video.

> [in regards to a question on what he meant by Debug config]: My own project's Debug configuration, not yours. Just the IOS environment. And we are not using the react native lib, just the cocoapod. The code I show in the video is from our native bindings, and only IOS uses Ably atm.

> Could be an IOS 11 issue... we are running ARKit in this app.

**Comment by ricardopereira** [comment]
@tcard You're right. It's not a leak.
I even tested it using the Leaks instruments and it's clean.
@mattheworiordan I have iOS 11 on my phone and it's working fine ¯\_(ツ)_/¯

**Comment by funkyboy** [comment]
Closing this as we cannot reproduce.
