### ISSUE TITLE
Objective-C tests review

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#627]
Our old tests were written in Obj-C and we use the new Swift tests for most of our test coverage now.  We should consider whether we can dispose of the old Obj-C tests completely or not by working out:

* [ ] How much of our coverage is provided by Obj-C tests
* [ ] How easy is it to simply get the Obj-C tests running
* [ ] How easy is it to port the test to Swift

**Comment by tcard** [comment]
There are only four spec items covered only by Objective-C:

- RSC14a
  * https://github.com/ably/ably-ios/blob/96720f7c03fa60c75f69b1d0384648248be499b2/ably-iosTests/ARTRestInitTest.m#L48
- RSL2a
  * https://github.com/ably/ably-ios/blob/96720f7c03fa60c75f69b1d0384648248be499b2/ably-iosTests/ARTRestChannelHistoryTest.m#L198
  * https://github.com/ably/ably-ios/blob/c56fffd1f8e0b2cc7ca0209eaabc19c084030b2f/ably-iosTests/ARTRestChannelHistoryTest.m#L150
  * https://github.com/ably/ably-ios/blob/c56fffd1f8e0b2cc7ca0209eaabc19c084030b2f/ably-iosTests/ARTRestChannelHistoryTest.m#L383
- RTP10d
  * https://github.com/ably/ably-ios/blob/5e4def84ad28da10840d521dbb65424c6b31d531/ably-iosTests/ARTRealtimePresenceTest.m#L1006
- RTP14d
  * https://github.com/ably/ably-ios/blob/96720f7c03fa60c75f69b1d0384648248be499b2/ably-iosTests/ARTRealtimePresenceTest.m#L754

They all look easy enough to port to Swift. I'd recommend that.

**Comment by mattheworiordan** [comment]
Thanks @tcard for reviewing this.

**Comment by ricardopereira** [comment]
@mattheworiordan Will do. Should I then deactivate those legacy tests?

**Comment by mattheworiordan** [comment]
> Should I then deactivate those legacy tests?

Yes, I think so personally so that we have a passing CI again.  @ricardopereira think you'll have time to look at this?

**Comment by ricardopereira** [comment]
Yes, maybe tomorrow or wednesday.

**Comment by mattheworiordan** [comment]
Thanks @ricardopereira
