### ISSUE TITLE
Carthage Install Error

### ISSUE THREAD

**Issue by riverbaymark** [ably/ably-ios#637]
Trying to install via Carthage attempts to pull an incorrect (earlier) version of SocketRocket. 

Mark

**Comment by levey** [comment]
I got the same issue.

**Comment by tcard** [comment]
I'm looking into this, and even after upgrading the SocketRocket version it doesn't seem to work. It has some conflicts with CocoaPods, but I haven't been able to figure out how to fix them.

I'm afraid I'll have to deprioritize this, though, as they are other documented ways of installing Ably that work. I'll come back to this when I can.

**Comment by mattheworiordan** [comment]
@tcard do we need to raise an issue upstream in SocketRocket?

**Comment by tcard** [comment]
@mattheworiordan The problem is with us, not with SocketRocket. Carthage and CocoaPods have a conflict, I guess due to some misconfiguration on our side. Xcode configuration is extremely convoluted, though, so it's not obvious (to me) what to do and I haven't found anything relevant over the Internet.

**Comment by mattheworiordan** [comment]
@ricardopereira can you help with this?

**Comment by ricardopereira** [comment]
Sure, I'll take a look.

**Comment by mattheworiordan** [comment]
Thanks @ricardopereira

**Comment by ricardopereira** [comment]
@riverbaymark @levey Could you test it using the `carthage-support` branch, please?

Cartfile example:

```
github "ably/ably-ios" "carthage-support"
```

**Comment by mattheworiordan** [comment]
@riverbaymark @levey did this help?

**Comment by riverbaymark** [comment]
Haven’t tried to reinstall with Carthage but will this week.

Thanks!

Mark Pruitt FNP, Co-CEO
Riverbay Softworks LLC 
‭(415) 656-8617‬
www.riverbaysoftworks.com

**Comment by riverbaymark** [comment]
Hi guys,

Looks like this did the trick!  I just added Ably to a new project via Carthage and everything built fine.

Thanks!

Mark

**Comment by mattheworiordan** [comment]
@riverbaymark thanks for trying it out, that's great news.  @ricardopereira should we merge and do a release soon then?  When you do, please be sure to follow the release process as we now ensure all releases go into our [product-wide changelog](http://changelog.ably.io)

**Comment by ricardopereira** [comment]
@riverbaymark Thanks!

Yes, I can merge it and do a release. @mattheworiordan Nice! Is that generated automatically?

**Comment by mattheworiordan** [comment]
> Nice! Is that generated automatically?

No, I take the markup from official releases at https://github.com/ably/ably-ios/releases and republish.

**Comment by riverbaymark** [comment]
Hi guys,

Just a suggestion for the documentation.  Be sure an tell folks to also drag over the KSCrash, msgpack, and SocketRocket frameworks along with the Ably framework or they will get a nasty "no matching architecture in universal wrapper” error

Keep up the great work guys!  Your service is awesome!

Mark

**Comment by ricardopereira** [comment]
Thanks for the suggestion.
Well, that's basically how Carthage works but it's always a nice thing to have. 👍
