### ISSUE TITLE
Presence map is using clientId as its key, rather than memberKey

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ios#641]
The lib solemnly set a memberKey for presence messages... and then ignores it and just uses the clientId as the key in the presence map.

https://github.com/ably/ably-ios/blob/7d18a06e190e6bd1fef7b879a258af521d6fcabe/Source/ARTPresenceMap.m#L109 https://github.com/ably/ably-ios/blob/7d18a06e190e6bd1fef7b879a258af521d6fcabe/Source/ARTPresenceMap.m#L128

So presence behaviour for clients which share a connectionId is currently completely broken.

See e.g. customer reporting an issue caused by this [here](https://app.intercom.io/a/apps/ua39m1ld/respond/inbox/all/conversations/12510079752) .

Relevant spec items: RTP2, RTP2a

**Comment by SimonWoolf** [comment]
Also:

- could we please have a test which enters multiple clients on one connection, leaves one, etc. No such test currently or this wouldn't been caught
- and perhaps some more tests of presence syncing? current test coverage looks a little thin. See e.g. https://github.com/ably/ably-js/blob/master/spec/realtime/sync.test.js for inspiration
- It looks like presence.get doesn't currently support filtering by clientId/connectionId, so also fails RTP11c2 and RTP11c3

**Comment by mattheworiordan** [comment]
@ricardopereira would you mind looking at this ASAP as this sounds like a pretty major bug?  Also, any idea why the issue was closed?
