### ISSUE TITLE
ARTMessage.data is not converting into Dictionary

### ISSUE THREAD

**Issue by gouravgupta72** [ably/ably-ios#643]
Hey folks,

Response in ARTMessage.data is coming as Any, when we try to convert it to Dictionary<String, Any> to get all payload information it is giving error.
 Can u help us in solving this.

if msg.data != nil {
            if let message = msg.data as! Dictionary <String, Any>
            {
               // Process message
            }
        }

**Comment by tcard** [comment]
Hi @gouravgupta72 . What's the error?

**Comment by gouravgupta72** [comment]
When trying to direct cast it's crashing and when doing above check it is saying 
"initializer of conditional binding must have optional type"

**Comment by tcard** [comment]
Does casting to NSDictionary work? We use NSJSONSerialization and I'm not sure the resulting NSDictionary can be bridged to a Dictionary<String, Any>.

**Comment by gouravgupta72** [comment]
No casting not working,
What would be the solution for getting response in dictionary form ?

**Comment by tcard** [comment]
OK, then it probably isn't being properly encoded as a JSON object. How are you publishing this? Can you share some code on the publishing end?

**Comment by gouravgupta72** [comment]
let messageForServer = ["intentName": "incoming_text",
                                "payload": [
                                            "text": message
                                            ],
                                "user": [
                                "type": "customer"
                                ]
        ] as [String : Any]
        
        self.channel?.publish(self.clientId, data: messageForServer, clientId: self.clientId) { error in
            guard error == nil else {
                self.signalError(error!)
                return
            }

**Comment by tcard** [comment]
This works for me:

```swift
self.channel.subscribe { (msg) in
    print("MESSAGE \((msg.data as! Dictionary<String, Any>)["hey"])")
}

self.channel.publish(nil, data: ["hey": 123])
```

Prints as expected:

```
MESSAGE Optional(123)
```

So I'm not sure what's going on with yours. Can you maybe print `String(describing: msg.data)` and `type(of: msg.data)`, see what it tells?

Can you confirm you're using the latest version of the library (1.0.9)?

**Comment by funkyboy** [comment]
@gouravgupta72 closing this. Feel free to reopen if it's still an issue.
FYI, current version of the SDK is now `1.0.10`.
