### ISSUE TITLE
Not getting message when app is in Background

### ISSUE THREAD

**Issue by gouravgupta72** [ably/ably-ios#653]
Hey Folks,

When i'm running app on simulator it's working fine, but on real device messages are not getting received when app is in background mode.

Can u help.

Thanks

**Comment by ricardopereira** [comment]
Hello @gouravgupta72 

It will happen in the simulator too if the app gets suspended. That's basically how iOS works. When an app enters background mode, it will suspend any network activity. It's a way to improve battery life. You can improve it using background fetch feature or just by sending silent notifications. Please have a look at the [App Programming Guide for iOS](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html). Thanks.

**Comment by gouravgupta72** [comment]
I try to use background fetch still it's not working for me.
Any other help guys ?

**Comment by tcard** [comment]
@gouravgupta72 You can use [push notifications](https://www.ably.io/documentation/realtime/push), which were designed specifically for this.

Please open a new issue if you have a specific problem with our iOS library. For general Ably questions, please refer to https://support.ably.io/support/home.
