### ISSUE TITLE
Log from ably-ios client in an inconsistent state

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ios#659]
See https://support.ably.io/helpdesk/attachments/3033171398 (@ricardopereira if you don't have access to that, let me know and I'll send it to you).

So as far as I can tell: the lib must be in the connected state as that's the only state in which an attach will reach the `ARTRealtime sending action 10 - Attach` stage. However, there's no response from Ably -- and more tellingly, no `ARTRealtime heartbeat received` messages, which indicates that it doesn't actually have an active connection, despite thinking it's `connected`.

@ricardopereira is that analysis correct? If so, then we really really need to prioritise https://github.com/ably/ably-ios/issues/638 , this is a really bad failure mode for the lib.

(couple other comments: (1) channel logs (state transitions etc) would be a lot more useful if they contained the channel name -- log above contains two channels, and the logs are annoying to analyse as a result. (2) channel log for the transition to `suspended` is printed twice for each channel; that may indicate a bug)

**Comment by ricardopereira** [comment]
> @ricardopereira is that analysis correct?

It makes sense to me. The `attach` checks if the [connection is active](https://github.com/ably/ably-ios/blob/b18503c87ab79f4d83bc2fa5da0681758b4ee4fe/Source/ARTRealtimeChannel.m#L862-L866) but for some reason it could  be in a bad state (maybe because of [this flag](https://github.com/ably/ably-ios/blob/b18503c87ab79f4d83bc2fa5da0681758b4ee4fe/Source/ARTRealtime.m#L879)).

Lets tackle #638 for now and I will have in mind the remaining comments. Thanks.

**Comment by johnpeb** [comment]
Hi @ricardopereira, could you provide an estimate when #638 may be implemented and released? This issue has affected several of our most active users (even though it's very difficult to reproduce locally). Thanks!

**Comment by ricardopereira** [comment]
@johnpeb I'll try to release a version tomorrow. I'll let you know when #638 is out. Thank you.

**Comment by johnpeb** [comment]
@ricardopereira  great to hear! Thanks!

**Comment by ricardopereira** [comment]
Idle timeout has been implemented in #660.

**Comment by ricardopereira** [comment]
@johnpeb Sorry for the late reply. We did a couple of changes and I just want to run a few more tests before releasing a version. I'll let you know when it's done. Thank you.

**Comment by ricardopereira** [comment]
The CI is still failing but I think it's almost done. Still some tests failing but I'm optimistic that tomorrow I can fix them all and release a version. Sorry for the waiting.

**Comment by johnpeb** [comment]
Great. We're looking forward to this release.

**Comment by ricardopereira** [comment]
[v1.0.10](https://github.com/ably/ably-ios/releases/tag/1.0.10) has been released.

Thank you for your patience!

**Comment by johnpeb** [comment]
Thanks!
