### ISSUE TITLE
Presence enter error coming

### ISSUE THREAD

**Issue by gouravgupta72** [ably/ably-ios#664]
Hi Folks,

When i'm calling enter presence then it is giving an error

presence.enter(nil) { error in
                guard error == nil else {
                    self.signalError(error!)
                    return
                }
            }

ARTErrorInfo with code 13, message: attempted to publish presence message without clientId, reason: (null)

**Comment by ricardopereira** [comment]
Hello @gouravgupta72. You need to provide a `cliendId`. 

> In order to be present on a channel, a client must be identified by having a client ID, have permission to be present, and be attached to the channel. [Ably Docs](https://www.ably.io/documentation/realtime/presence)

**Comment by gouravgupta72** [comment]
Hi I tried subscribe channel and then enter presence still getting the same error, we are using token authentication.

guard let channel = self.channel else { return }
        let presence = channel.presence
        
        channel.attach(){ error in
        }
        presence.subscribe(self.membersChanged)
        channel.subscribe(self.receiveMessage)
        delay(1.0) {
            presence.enter("") { error in
                guard error == nil else {
                    self.signalError(error!)
                    return
                }
            }
        }

**Comment by funkyboy** [comment]
@gouravgupta72 Thanks for getting in touch. A few questions.

### Enable logging
Can you please enable a more verbose logging to see what's going on?
```
options.logLevel = .verbose
let client = ARTRealtime(options: options)
```

### Log errors (if any)
Can you please check if there's any error along the way? E.g.
```
channel.attach(){ error in
  // print error here if not nil
}
```

### Provide a clientId
Does your instance of `ARTRealtime` have a `clientId` set? E.g.
```
options.clientId = "myClientId"
```

**Comment by gouravgupta72** [comment]
hey,
i got the error and now it working.
Thanks for the help.

**Comment by gouravgupta72** [comment]
Hi Folks,

When i'm trying to update user presence from my code no action is having, when doing the same from ably consol it's working fine.

let channel = realtime.channels.get("ate-dad-fly")
channel.presence.subscribe(.Enter) { member in
    print("Member \(member.clientId) entered")
}
channel.presence.enter(nil)

Can you please help me in getting update user presence?

**Comment by funkyboy** [comment]
@gouravgupta72 With JWT you can use a clientId. See the documentation here: https://www.ably.io/tutorials/jwt-authentication

**Comment by gouravgupta72** [comment]
Hey @funkyboy ,

this is the debug log we are getting

"token":{"token":"key_name-S3bidW4uF8zqqm_AwKRXPNQdvR7QCOoryx9ocl62tXhTiRWRqwkSUpqSDmCjAMoqOhA9HezDHtRN2kTqlbGfghpNjolzb4WYwWolSMAL4FlJ749thea6d4BtVAjxyfAXf559_DA---SrFNgUSoyUA","keyName":"key_name.P__eEQ","issued":1533624962493,"expires":1533628562493,"capability":"{\"*\":[\"publish\",\"subscribe\"]}","clientId":"Bob"}}

It is showing that client id is assign to my token, but when i'm trying to enter my presence i'm still not able to see it in dev consol.

Only 1 member is showing for which i added presence from dev consol.

**Comment by funkyboy** [comment]
@gouravgupta72 I think that's because you don't have capabilities for presence. See docs here: https://www.ably.io/documentation/general/authentication#capabilities-explained
So you should have something like:

`"capability":"{"*":["publish","subscribe","presence"]}"`

**Comment by gouravgupta72** [comment]
Thanks for the help.

It worked.
