### ISSUE TITLE
Push test is failing but it was passing (no code has been changed)

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#669]
https://github.com/ably/ably-ios/blob/b9c0951b982399003935f3c9d89dc87343776894/Spec/PushAdmin.swift#L216-L241

I chatted with @paddybyers about this issue.
I updated the code 
`realtime.push.admin.publish(["ablyChannel": channel.name], data: ["data": ["foo": "bar"]])`

to

`realtime.push.admin.publish(["transportType": "ablyChannel", "channel": channel.name, "ablyKey": options.key, "ablyUrl": options.restUrl() data: ["data": ["foo": "bar"]])`

but even so the `__ably_push__` doesn't get the message/notification.

**Comment by paddybyers** [comment]
@mezis can you help with this pls?

**Comment by mezis** [comment]
@ricardopereira, @paddybyers — assuming you've been running tests against `sandbox`, I never got tests to pass against that. I don't even know if `sandbox` is serviced by queue workers.
All my testing has been against a local farm , and running the `queue-workers` branch of `realtime`.

@mattheworiordan, how can we get an environment that runs the appropriate branch of `realtime` including queue workers?

**Comment by funkyboy** [comment]
@ricardopereira Is this still an issue? It doesn't look like but I might be wrong.

**Comment by ricardopereira** [comment]
@funkyboy Yes, I think it's still an issue.

The test suite passes because the test is pending: https://github.com/ably/ably-ios/blob/4c3bc4d98b4624c0c407159e7f91e4fe6b54cdb9/Spec/PushAdmin.swift#L216

**Comment by ricardopereira** [comment]
^ Sorry. I pushed the wrong button.

**Comment by funkyboy** [comment]
@paddybyers @ricardopereira what's the spec item related to this test?

**Comment by paddybyers** [comment]
RSH1a I guess
