### ISSUE TITLE
Channels Failing After Some times and do not resubscribe

### ISSUE THREAD

**Issue by shoaibahmedqureshi** [ably/ably-ios#670]
I am running into an strange issue where after disconnection my channels start failing and even after re-subscription i am unable to subscribe they either fail or or do not return any thing and the reason for those channels to fail in the logs is also nil.

My Configurations are .....
    private func setClientOptions(token: String?) {
          if token != nil {
              options = ARTClientOptions(token: token!)
          }
        else {
              options = ARTClientOptions(key: ablyKey!)
        }
             options!.autoConnect = true
            options!.queueMessages = false
             options!.logLevel = ARTLogLevel(rawValue: UInt(Configuration.ablyLogLevel!))!
   }

My subscribe method is 

    private func subscribeChannel(channelName: String, notUsed: Bool) throws -> Bool {
        
        if (Validator.isValidChannel(channel: channelName)) {
            let channelFullName = MessagingHelper.getChannelWithNameSpace(name: channelName)
            
              DDLogDebug("\(tag) Subscribing... to channel \(channelFullName)")
              DispatchQueue.global(qos: .background).async {
                if (!self.isConnected()) {
                    self.connectToRTClient()
                }
               let channel = self.ablyRealtime!.channels.get(channelFullName)
               self.channelStateChange(channelName:channelFullName)
               channel.subscribe { message in
                self.handleMessage(channel: channelFullName, message: message.data as! String)
              }
            }
            return true
        } else {
            print("\(tag) Invalid channel \(channelName)")
        }
        
        return false
    }

i am tracking change in channels state in this method

    private func channelStateChange(channelName:String) {
        let channel = ablyRealtime!.channels.get(channelName)
        channel.on { stateChange in
            print("channel \(channel.name) is now attached")
            switch stateChange?.current {
            case .initialized?:
                DDLogInfo("Channel - Initialized!")
                break
            case .attached?:
                DDLogInfo("Channel - Attached")
                break
            case .none:
                DDLogInfo("Channel - none")
                DDLogInfo("channel \(channel.name) reason \(stateChange?.reason)")
                break
            case .suspended?:
                DDLogInfo("Channel - suspended")
                DDLogInfo("channel \(channel.name) reason \(stateChange?.reason)")
                break
            case .detached?:
                DDLogInfo("Channel - detached")
                DDLogInfo("channel \(channel.name) reason \(stateChange?.reason)")
                break
            case .detaching?:
                DDLogInfo("Channel - detaching")
                DDLogInfo("channel \(channel.name) reason \(stateChange?.reason)")
                break
            case .attaching?:
                DDLogInfo("Channel - attaching")
                DDLogInfo("channel \(channel.name) reason \(stateChange?.reason)")
                break
            case .failed?:
                DDLogInfo("Channel - Failed")
                DDLogInfo("channel \(channel.name) reason \(stateChange?.reason)")
                if self.shouldRetry(channelName:channelName) == true {
                   client.subscribe(channelName:channelName)
                }
                break
            default:
                break
            }
        }
    }

here it is my reconnect method 

    private func reconnect() {
        DispatchQueue.global(qos: .background).async {
        if (self.ablyRealtime != nil) {
            self.ablyRealtime!.connection.close()
            //ablyRealtime!.channels.clear()
            self.ablyRealtime!.close()
            self.ablyRealtime!.connect()
            self.ablyRealtime?.connection.connect()
        }
      }
       

I am  reconnecting Ably and then resubscribing explicitly after this situation in this case but even then the ably connection is established but channels are not subscribed and i can see heartbeat in logs indicating that my connection is alive but channels are not subscribed . I am attaching all the logs in the file below. Any help would be appreciated.
[AblyLogs.txt](https://github.com/ably/ably-ios/files/1644892/AblyLogs.txt)

**Comment by paddybyers** [comment]
@funkyboy a few comments on the code snippets above and log:

- on every state change it prints `print("channel \(channel.name) is now attached")` - irrespective of the channel state. You need to check the other lines to see what's actually happening;

- if the channel enters the `failed` state, it does:

```
            if self.shouldRetry(channelName:channelName) == true {
               client.subscribe(channelName:channelName)
            }
```

I suspect that that might be just adding the listener again to the channel, and not triggering a new attach. I think you should have a look at whether or not that's the problem.

@shoaibahmedqureshi when is `reconnect()` being called?

The other worrying thing in the log is we see:

```
2018-01-19 04:23:23.249466+0500 myTrackee[88304:6147378] Channel - Failed
2018-01-19 04:23:23.249891+0500 myTrackee[88304:6147378] channel public:demobus reason nil
```

It shouldn't be possible for there to be a `failed` state transition for a channel without any indicated `reason`.

**Comment by shoaibahmedqureshi** [comment]
I call reconnect method when i receive no messages and channels are failing so I have a button which calls reconnect ably explicitly on its click.

**Comment by paddybyers** [comment]
@shoaibahmedqureshi so I think your code:

```
        case .failed?:
            DDLogInfo("Channel - Failed")
            DDLogInfo("channel \(channel.name) reason \(stateChange?.reason)")
            if self.shouldRetry(channelName:channelName) == true {
               client.subscribe(channelName:channelName)
            }
```

should be doing a `channel.attach()` instead of a `client.subscribe()`. I'd also like to see a `DDLogInfo()` added so we can see if that's actually happening (ie after the `shouldRetry()` check).

**Comment by shoaibahmedqureshi** [comment]
After should try i added a DDLlogInfo and it is printing you can see that a new log file . I think the problem which randomly occurs is initially a channel attached and then it is detached with reason(null) . why is it detached ? then resubscription fails so the problem seems to have two parts.

             case .failed?:
                DDLogInfo("Channel - Failed")
                DDLogInfo("channel \(channel.name) reason \(String(describing: stateChange?.reason))")
                if self.shouldRetry(channelName:channelName) == true {
                   DDLogInfo("channel resubscribing after failure ....")
                   client.subscribe(channelName:channelName)
                }
                break


[AblyLogs.txt](https://github.com/ably/ably-ios/files/1648128/AblyLogs.txt)

**Comment by funkyboy** [comment]
@shoaibahmedqureshi as a side note:
I see you are using version `1.0.9` of the SDK. Does this happen also on `1.0.10`, our latest stable version?

**Comment by shoaibahmedqureshi** [comment]
paddybyers Thanks alot for your response it was that same issue you pointed  I was not attaching the channels . apologies for my previous comment I could read your response completely initially . @funkyboy  I cannot use the latest version as https://github.com/ably/ably-ios/commit/f5fc0531912049bdadecc451b3b8429290880cf3 is not merged to 1.0 yet.

**Comment by funkyboy** [comment]
@paddybyers ^ FYI

**Comment by funkyboy** [comment]
@shoaibahmedqureshi closing this. Feel free to reopen if needed.
