### ISSUE TITLE
Uncaught Exception: '-[__NSCFURLSessionConnection performDefaultHandlingForAuthenticationChallenge:]: unrecognized selector

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#674]
Reported crash on device:

# SDK version: 1.0.5
# OS Version: 11.2.2 (15C202)
# Device: iPhone X

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFURLSessionConnection performDefaultHandlingForAuthenticationChallenge:]: unrecognized selector sent to instance 0x7ff06d958410'
```

Crash report is at https://app.intercom.io/a/apps/ua39m1ld/respond/inbox/conversation/14348764648

Possibly related: https://stackoverflow.com/questions/27604052/nsurlsessiontask-authentication-challenge-completionhandler-and-nsurlauthenticat

Question: Is this crash happening during reporting of an issue i.e. sentry error reporting, and thus it's crashing the apps as opposed to handling the error and moving the connection to the failed state with a suitable error?

**Comment by funkyboy** [comment]
UPDATE: waiting for customer to confirm that this happens also on `1.0.10`

**Comment by ricardopereira** [comment]
This has been fixed in the `push` branch, see: https://github.com/ably/ably-ios/blob/b9c0951b982399003935f3c9d89dc87343776894/Source/ARTURLSessionServerTrust.m#L45

The commit with that change is https://github.com/ably/ably-ios/pull/642/commits/28134c2f081be1555cccb5f5fe3b1a968a77b23c

**Comment by ricardopereira** [comment]
@funkyboy Should we fix it on `master` as well and do a patch release?

**Comment by funkyboy** [comment]
@ricardopereira yes please. Make a PR just with that change, so we can make a patch release.

**Comment by ricardopereira** [comment]
@funkyboy Done ^

**Comment by funkyboy** [comment]
Fixed in https://github.com/ably/ably-ios/pull/676
