### ISSUE TITLE
Remove authorise 

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-ios#677]
V1 is out and this is already been [tagged as deprecated](https://github.com/ably/ably-ios/blob/2027ee3690f5fa2af3c1f629d8471934d6e79348/Source/ARTAuth.h#L48).
I think we can remove it in the next version. Agree? @ricardopereira

**Comment by ricardopereira** [comment]
@funkyboy Agree. Thanks.

**Comment by funkyboy** [comment]
Fixed in #679
