### ISSUE TITLE
Investigate iOS8 usage

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-ios#685]
How many customers are still using our SDK with iOS8?

User-Agent strings:

- iOS 8.4 `CFNetwork/711.4.6 Darwin/14.0.0`
- iOS 8.3 `CFNetwork/711.3.18 Darwin/14.0.0`
- iOS 8.2 `CFNetwork/711.2.23 Darwin/14.0.0`

For reference: iOS 11.2.5 `CFNetwork/894 Darwin/17.4.0`

**Comment by ricardopereira** [comment]
@funkyboy Why not using different jobs for each iOS version? That way it's easier for me to see which version is failing and the log could remain clean.

![hnmfd](https://user-images.githubusercontent.com/3541185/35855923-6f8fc9c0-0b2c-11e8-9df7-e98b24a59b79.jpg)

**Comment by funkyboy** [comment]
@ricardopereira that would make a lot of sense. Do you know how they do that? GH hooks maybe? 
That said we are trying to avoid hosting Jenkins. And as far as I know, with our current setup we can trigger only one "action" on Travis, which currently is "run tests in a sequence".

**Comment by ricardopereira** [comment]
@funkyboy I took that image from https://stackoverflow.com/questions/47545727/trigger-multiple-jenkins-builds-with-github-pull-request-builder

**Comment by funkyboy** [comment]
@ricardopereira yep, that's cool. I'll see if we can have something like that without using Jenkins. It's complicated to maintain for us at the moment.

**Comment by ricardopereira** [comment]
That would be perfect. Thanks!

**Comment by funkyboy** [comment]
@ricardopereira Not exactly what you asked but ... :)
![screen shot 2018-02-08 at 15 11 42](https://user-images.githubusercontent.com/348355/35977099-765d1f16-0ce2-11e8-801f-b691a403f90e.png)

See https://travis-ci.org/ably/ably-ios/builds/338994585

**Comment by ricardopereira** [comment]
Cool!

![image 2018-02-08 at 7 56 41 pm](https://user-images.githubusercontent.com/3541185/35995112-55bed1c8-0d0a-11e8-894d-aad2fc8a93f2.png)

**Comment by funkyboy** [comment]
Percentage of iOS8 traffic with respect to total traffic. Measured on frontends (26) today.

```
0
0
0
0
.00146258969788381553
.00108820893611573422
.00013199577613516367
.00002827214769369955
.00002437993693722978
.00007934258996882969
0
.00003431826761385085
0
.00005482606431097343
0
.00002298639205590290
.00002817271754033394
0
0
.00002953162837398854
0
0
.00001403508771929824
0
0
0
```

Total average is `0.00011533304778264694`.

cc @paddybyers @ricardopereira
