### ISSUE TITLE
Address msgpack warnings

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-ios#689]
When using Cocoapods

![screen shot 2018-02-09 at 10 40 25](https://user-images.githubusercontent.com/348355/36021321-b57f5350-0d85-11e8-9b5f-19565e80a106.png)

**Comment by funkyboy** [comment]
PR sent [here](https://github.com/rvi/msgpack-objective-C/pull/2)

**Comment by funkyboy** [comment]
Update here: https://github.com/rvi/msgpack-objective-C/pull/3

**Comment by ricardopereira** [comment]
Addressed with [MsgPack Ably Fork](https://github.com/ably-forks/msgpack-objective-C).
