### ISSUE TITLE
App Store publication issues when using Carthage

### ISSUE THREAD

**Issue by makoni** [ably/ably-ios#698]
There're few issues with publishing to App Store if you add Ably through.

Tha app builds and runs but when you're making an archive and upload it to App Store it won't be validated. Errors while validating:

```
iTunes Store Operation Failed
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.facebook.socketrocket.ios' under the iOS application 'myApp.app'.

iTunes Store Operation Failed
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.remyvirin.msgpack' under the iOS application 'myApp.app'.

iTunes Store Operation Failed
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.stenerud.KSCrash' under the iOS application 'myApp.app'.

iTunes Store Operation Failed
This bundle Payload/myApp.app/Frameworks/Ably.framework/Frameworks/SocketRocket.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion.

iTunes Store Operation Failed
This bundle Payload/myApp.app/Frameworks/SocketRocket.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion.

iTunes Store Operation Failed
Invalid Bundle. The bundle at 'myApp.app/Frameworks/Ably.framework' contains disallowed nested bundles.

iTunes Store Operation Failed
Invalid Bundle. The bundle at 'myApp.app/Frameworks/Ably.framework' contains disallowed file 'Frameworks'.
```

Is there a chance in will be fixed?

Here's how signing screen looks like:
<img width="737" alt="2018-02-22 16 05 57" src="https://user-images.githubusercontent.com/234015/36540327-fbfb0fb2-17ea-11e8-87fe-eae7b8a44473.png">

**Comment by funkyboy** [comment]
@makoni Thanks for reporting this.
Which version of the SDK are you using?

**Comment by makoni** [comment]
I used latest Xcode 9.2 with iOS 11 SDK

**Comment by funkyboy** [comment]
@makoni That's also good to know. 

I was asking about the version of the Ably SDK :)
What's your `Cartfile` like?

**Comment by makoni** [comment]
github "ably/ably-ios" == 1.0.11

I had the same issues with github "ably/ably-ios" ~> 1.0

**Comment by funkyboy** [comment]
Thanks. What version of Carthage are you using? (`carthage version` in the terminal)

**Comment by makoni** [comment]
0.28.0

**Comment by funkyboy** [comment]
Is your app including an App Extension by chance?

**Comment by makoni** [comment]
No, just iOS app without extensions

**Comment by makoni** [comment]
Here's how my Carthage build folder looks like if it can help:

<img width="730" alt="2018-02-22 17 20 07" src="https://user-images.githubusercontent.com/234015/36543402-b829dcbe-17f4-11e8-90aa-4faa3dd3356b.png">

**Comment by funkyboy** [comment]
There's a duplication on the file system but likely there's also one in the Xcode project.

In the General what's "Linked Frameworks and Libraries" like?

**Comment by makoni** [comment]
Like in README screenshot:
https://github.com/ably/ably-ios/blob/master/Examples/Images/linked-frameworks.png

**Comment by funkyboy** [comment]
Can you please get rid of the Carthage build folder and anything related to Carthage in the project, and then run `carthage update --no-use-binaries`?

**Comment by makoni** [comment]
I made an empty Xcode project which you can use to reproduce all issues. Just change bundle id and team to yours and try to archive and validate:

[ablyTest.zip](https://github.com/ably/ably-ios/files/1748299/ablyTest.zip)

**Comment by funkyboy** [comment]
Will try now. Thanks.

**Comment by funkyboy** [comment]
@makoni The solution (workaround?) I found is to delete this folder.
![screen shot 2018-02-22 at 16 03 05](https://user-images.githubusercontent.com/348355/36545758-f65817ea-17e9-11e8-8503-21fc8009b27f.png)

Not ideal, but at least you can submit your app :)
Will keep this issue open because it needs investigation.

Thanks for your help so far!

**Comment by funkyboy** [comment]
If you hit the SocketRocket missing `CFBundleVersion` value just add this to the SocketRocket Info.plist.
![screen shot 2018-02-22 at 16 12 18](https://user-images.githubusercontent.com/348355/36546273-474204a8-17eb-11e8-8a99-9c967bc0e417.png)

**Comment by funkyboy** [comment]
As for the SocketRocket error I send a PR here: https://github.com/facebook/SocketRocket/pull/559

**Comment by funkyboy** [comment]
I created a separate issue for the "SocketRocket missing CFBundleVersion" problem [here](https://github.com/ably/ably-ios/issues/701)

**Comment by funkyboy** [comment]
@makoni This is now fixed in version `1.0.12`

**Comment by bhargavbajani** [comment]
A duplicate framework issue is happening in latest version >= 1.2.16 

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/13344552/205957347-96a15ff9-9654-43fc-bc99-7dfd4cff9d84.png">

**Comment by makoni** [comment]
> @makoni can you reopen this?

Unfortunately there's no reopen button. Try to open a new issue
