### ISSUE TITLE
Run CI on develop after a branch is merged

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-ios#699]

**Comment by paddybyers** [comment]
I assumed that all pushes to all branches would trigger CI. Can we not do that?

**Comment by funkyboy** [comment]
I removed that, otherwise we'd have to 2 builds anytime we push to a branch that is part of a PR: one for the branch and one for the PR.

Now it triggers only when you push to a branch that is part of a PR.

Much like [I did with JS](https://github.com/ably/ably-js/pull/471) I'll trigger builds only on master.

**Comment by paddybyers** [comment]
If we're following the git process I proposed, then it wouldn't be pushes to `master` that matter; it would be those to `develop` and/or a release branch. I do think that we should instigate that process and then configure CI appropriately.
