### ISSUE TITLE
SocketRocket - missing required key when submitting to the App Store

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-ios#701]
When submitting to the App Store you might stumble upon this error.
![36663405-c3f5be42-1ae1-11e8-9baf-b6880647c50d](https://user-images.githubusercontent.com/348355/36692025-3c471120-1b37-11e8-866e-9d32a108aa70.png)

This is an issue with SocketRocket. I sent a PR to fix it [here](https://github.com/facebook/SocketRocket/pull/559).

In the meantime, the workaround is to manually add a value for `CFBundleVersion` in the Info.plist of SocketRocket. See example below.

![36546273-474204a8-17eb-11e8-8a99-9c967bc0e417](https://user-images.githubusercontent.com/348355/36692160-a4018dc2-1b37-11e8-8dac-2981b6378633.png)

**Comment by mattheworiordan** [comment]
Superseded by https://github.com/ably/ably-ios/issues/803
