### ISSUE TITLE
Use of NSURLConnection

### ISSUE THREAD

**Issue by gouravgupta72** [ably/ably-ios#712]
Hi Folks,

KSCrashlyticsAblyFork is still using depreciated NSURLConnection, can we update it.

NSData* data = [NSURLConnection sendSynchronousRequest:request
                                                 returningResponse:&response
                                                             error:&error];

Thanks,

**Comment by gouravgupta72** [comment]
Hi @funkyboy 

I had updated to the latest version.

Using KSCrashAblyFork (1.15.8-ably-2)

It is still using this library.

**Comment by funkyboy** [comment]
Oh, there's been a little misunderstanding. It's `KSCrashAblyFork`, not `KSCrashlyticsAblyFork` :)

That said, even if we updated to the latest upstream, that [still uses the `NSURLConnection` API](https://github.com/kstenerud/KSCrash/blob/2bb7ea35edab490105647d9b0081168e131ad22d/Source/KSCrash/Reporting/Tools/KSHTTPRequestSender.m#L108), so there's little point in updating at the moment.

**Comment by gouravgupta72** [comment]
ohh,

Is it possible that we can raise a request for updating it ?

**Comment by funkyboy** [comment]
@gouravgupta72 You can raise an issue in the [upstream repo](https://github.com/kstenerud/KSCrash)

BTW that code is wrapped by [this macro](https://github.com/ably-forks/KSCrash/blob/master/Source/KSCrash/Reporting/Tools/KSHTTPRequestSender.m#L102). 
If you are targeting iOS8+, that code will be excluded at compile time.

**Comment by funkyboy** [comment]
Closing this. Feel free to reopen as you see fit.
