### ISSUE TITLE
Investigate implementation of RTN15a

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-ios#727]
https://docs.ably.io/client-lib-development-guide/features/#RTN15a says 
"If a Connection transport is disconnected unexpectedly or if a token expires, then the Connection manager will immediately attempt to reconnect and restore the connection state."

Looking at [the current implementation](https://github.com/ably/ably-ios/blob/67d1d943ceba3181a035df8e599fb9b10a5fd618/Source/ARTRealtime.m#L489) it seems like connection retries are always timer based and the first is not tried right away.

Some discussion here https://github.com/ably/ably-ios/pull/726#issuecomment-389637832

**Comment by ricardopereira** [comment]
@mattheworiordan Is this the bug (does not retry a connection when it fails immediately, it waits 15s now) that you talked about?

**Comment by mattheworiordan** [comment]
Yes

**Comment by ricardopereira** [comment]
@funkyboy Paddy told me that you will handle this, is that right?

**Comment by funkyboy** [comment]
Fixed in #789
