### ISSUE TITLE
Delegate method for message received while app in background mode

### ISSUE THREAD

**Issue by PShantanu** [ably/ably-ios#728]
Hi folks, we are planning to use Ably in one of our iOS & Android application. We are able to publish /subscribe and do all other stuff, but wondering whether when the iOS app is in background mode and the app receives a message , is there any delegate method that gets hit?

**Comment by funkyboy** [comment]
Hi @PShantanu, thanks for getting in touch.

On iOS the app follows the directives of the operative system. So if the app is in background the connection will disconnect and it will reconnect when the app is opened again. 
While iOS allows you to [ask for a grace period when entering background](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW3) that will not keep Ably's connection open indefinitely. 

You can fetch messages that were sent when the app was offline using the [history API](https://github.com/ably/ably-ios#querying-the-history)

If you think there's some iOS API that we can leverage to improve Ably's behavior when an app is in background let us know :)

**Comment by PShantanu** [comment]
Thanks @funkyboy for your prompt reply which clarifies all our doubts :)
