### ISSUE TITLE
Issue while subscribe device for Push Notifications

### ISSUE THREAD

**Issue by gouravgupta72** [ably/ably-ios#796]
### Which version of the Ably SDK are you using? 
 Ably (1.1.0)

### On which platform does the issue happen? 
iOS11

### Are you using Carthage? 
No

### Are you using Cocoapods? 
Yes 

### Which version of Xcode are you using? 
9.4.1

### What did you do?
I want to subscribe for push notification, i had added capabilities with my token and also gave permission in channel.

When i'm trying to subscribe my device, method is showing error
```
Add a short snippet of code to show the problem
```
realtime.channels.get("pushenabled:foo").subscribeDevice { error
    // Check error.
}

What is the type of this realtime object, and how i can get this from my existing connection object.

**Tip:** set the log level to debug. E.g. `realtime.logger.logLevel = .debug` and take a look at our [troubleshooting guide](https://support.ably.io/solution/articles/3000063743-guide-information-we-need-to-help-you-diagnose-problems)

### Link to sample project
Feel free to link to a sample project that showcases the issue.

P.S. If you are an [Ably Enterprise customer](https://www.ably.io/pricing/enterprise), please [get in touch](https://www.ably.io/contact) with a link to this issue to get prioritized support.

**Comment by gouravgupta72** [comment]
I'm not able to get the type of realtime object

```
realtime.channels.get("pushenabled:foo").subscribeDevice { error
// Check error.
}
```

Also when trying to send message for push support the same object is used, how i will get that object from current . channel?

**Comment by ricardopereira** [comment]
@gouravgupta72 Thank you for opening an issue.

To understand what's the issue you're facing, could you clarify "I'm not able to get the type of realtime object".

What's the `error` saying?

> Also when trying to send message for push support the same object is used, how i will get that object from current . channel?

You can keep the channel by assigning it to a variable like `let channel = realtime.channels.get("pushenabled:foo")` and use it. Is that what you wanted to know?

**Comment by ricardopereira** [comment]
@gouravgupta72 Exactly, you need to create the object using your app key like `let realtime = ARTRealtime(key: "your:key")`. Please have a look at our [iOS Demo app](https://github.com/ably/demo-mobile-ios). Thank you

**Comment by gouravgupta72** [comment]
Hi @ricardopereira 

When i'm trying to register for push notification logs are getting stopped with status ARTPushActivationStateWaitingForPushDeviceDetails

```
 func registerForNotificationAbly(ably: ARTRealtime)
    {
        if let token = defaults.value(forKey: "deviceTokenAbly") as? Data {
            ARTPush.didRegisterForRemoteNotifications(withDeviceToken: token, realtime: ably)
            ably.push.activate()
        }
    }
```

```
    func didActivateAblyPush(error: ARTErrorInfo?) {
         
         if let error = error {
             // Handle error
             return
         }
         print("Success")
         // Subscribe to channels / listen for push etc.
     }

```

Here is my code i wrote in AppDelegate.

What is the issue why i'm not getting success or failure call back.

**Comment by ricardopereira** [comment]
@gouravgupta72 Are you testing your in a simulator or in a physical device? Push Notifications aren't available in simulators. That could be the problem.

**Comment by gouravgupta72** [comment]
No i'm using real phone.

Also i'm not creating ably connection on launch, i'm doing this after some time.
So i'm not able to find any protocol method as well which i can inherit in app delegate.

**Comment by ricardopereira** [comment]
@gouravgupta72 You can't find the `ARTPushRegistererDelegate`? Is that it?

**Comment by gouravgupta72** [comment]
Yes.

Can i have any sample code for Push notification which i can reffer

**Comment by ricardopereira** [comment]
@gouravgupta72 Yes, please provide a sample project to look at.

**Comment by gouravgupta72** [comment]
Hey @ricardopereira 

Here is the sample code 

https://github.com/gouravgupta72/chatDemo.git

**Comment by ricardopereira** [comment]
@gouravgupta72 Sorry, but that project doesn't work. Please review it.

CLI details:

```
➜  chatDemo-master pod install

[!] Invalid `Podfile` file: syntax error, unexpected tXSTRING_BEG, expecting keyword_end
 pod 'Ably'`
            ^
/Users/ricardopereira/Downloads/chatDemo-master/Podfile:9: unterminated string meets end of file.
```

**Comment by gouravgupta72** [comment]
@ricardopereira 
Please check again i had fixed that issue,
sorry for the inconvenience.

**Comment by ricardopereira** [comment]
@gouravgupta72 So, I compiled your sample and it's working. The `ARTPushRegistererDelegate` is recognised. You just need to add the `ARTPushRegistererDelegate` protocol to your AppDelegate.

**Comment by ricardopereira** [comment]
A simple sample of Push Notification:

```swift
import UIKit
import Ably
import UserNotifications

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, ARTPushRegistererDelegate {

    var window: UIWindow?
    var realtime: ARTRealtime!

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        realtime = ARTRealtime(key: "xxxx:xxxx")

        UNUserNotificationCenter.current().delegate = self

        requestPushNotificationPermissions()
        return true
    }

    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        ARTPush.didRegisterForRemoteNotifications(withDeviceToken: deviceToken, realtime: realtime)
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        ARTPush.didFailToRegisterForRemoteNotificationsWithError(error, realtime: realtime)
    }

    func didActivateAblyPush(_ error: ARTErrorInfo?) {
        print("Ably Push Actvation:", error ?? "no error")
        // Ready to receive notifications
    }

    func didDeactivateAblyPush(_ error: ARTErrorInfo?) {
        print("Ably Push Deactvation:", error ?? "no error")
    }

    private func requestPushNotificationPermissions() {
        let options: UNAuthorizationOptions = [.alert, .badge, .sound]
        UNUserNotificationCenter.current().requestAuthorization(
            options: options,
            completionHandler: { granted, error in
                DispatchQueue.main.async {
                    UIApplication.shared.registerForRemoteNotifications()
                }
            }
        )
    }

}

extension AppDelegate: UNUserNotificationCenterDelegate {

    func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        // TODO: handle received remoteNotification: response.notification.request.content.userInfo
        completionHandler()
    }

    func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        completionHandler([.alert])
    }

}
```

**Comment by gouravgupta72** [comment]
I'm doing the same

but didActivateAblyPush is not getting called.

Can you please check my code and provide me solution what i missed?

**Comment by ricardopereira** [comment]
@gouravgupta72  Your code is missing the `ARTPushRegistererDelegate` delegate. See https://github.com/gouravgupta72/chatDemo/blob/09c63281b9f55fafa5dac80b1493ba099e3d9b06/chatDemo/AppDelegate.swift#L14

You need this:

```
class AppDelegate: UIResponder, UIApplicationDelegate, ARTPushRegistererDelegate
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
...
```

**Comment by gouravgupta72** [comment]
Thanks,

It's worked.

But now when i'm trying to subscribe by device id

> realtime.channels.get("pushenabled:foo").subscribeDevice { error
>     // Check error.
> }

It is saying  `Value of type 'ARTRealtimeChannel' has no member 'subscribeDevice'`

**Comment by ricardopereira** [comment]
@gouravgupta72 Sorry, the documentation is not updated. That member is now available in the `ARTPushChannel`.

```swift
realtime.channels.get("pushenabled:foo").push.subscribeDevice() { error in
    // Check error            
}
```

**Comment by gouravgupta72** [comment]
Thanks,

Last issue i have, when i'm trying to submit any message with push notification extra, it is giving me error

`ARTErrorInfo with code 40000, message: Published push notification to not push-enabled channel`

I had enable push notification for my app as well as try to create new channel rule which has nameSpace of my channel prefix.

Can you provide rules creation sample or structure, may be all my channel taking default rules by-default.


<img width="962" alt="screen shot 2018-10-04 at 12 43 32 pm" src="https://user-images.githubusercontent.com/6007522/46458370-29e99180-c7d3-11e8-9b40-31fd99b485b0.png">

**Comment by SimonWoolf** [comment]
@gouravgupta72 To help you with this, could you please tell us the channel name you're using, and [the app id](http://support.ably.io/support/solutions/articles/3000063083-how-do-i-find-my-app-id-) of the app you're using.

**Comment by gouravgupta72** [comment]
channel name is EK7687886, and app id is 
`J0GNIQ`

**Comment by SimonWoolf** [comment]
> channel name is EK7687886

Then that's your issue. That channel is not part of the `namespace-EK` namespace. Please read http://support.ably.io/support/solutions/articles/3000030058-what-is-a-channel-namespace-and-how-can-i-use-them-

**Comment by gouravgupta72** [comment]
so what should be the rule is should set for this type of channel name which will start with EK

**Comment by SimonWoolf** [comment]
Namespaces don't work on name prefixes. They work on the full name, or the first `:`-delimited segment. So only a `EK7687886` namespace will match `EK7687886`, but an `EK` namespace would match `EK:7687886` (note the comma). This is all explained in the support article I linked in my previous comment.

**Comment by ayansarkarIOStechnoexponent** [comment]
self.channel = self.ablyClient.channels.get(getMyPushChannelName())
        self.channel?.push.subscribeDevice()
        self.ablyClient.channels.get(getMyPushChannelName()).push.subscribeDevice { error in
            // Check error.
            print(error)
        }

i get this error 

Optional(Error 0 - cannot use device before device activation has finished)

anyone please tell me whai is the reason
