### ISSUE TITLE
Unable to submit to AppStore

### ISSUE THREAD

**Issue by hliu2000** [ably/ably-ios#803]
### Which version of the Ably SDK are you using? 
1.1.0

### On which platform does the issue happen? 
iOS

### Are you using Carthage? 
Yes, 0.28.0

### Are you using Cocoapods? 
No

### Which version of Xcode are you using? 
Xcode 9.2

### What did you do?
We are trying to use Ably in our iOS app, everything is fine until when we submit it to AppStore, got the error from iTunes Connect:
```
ERROR ITMS-90056: "This bundle Payload/OurApp.app/Frameworks/SocketRocket.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."
```

This issue is caused by the SocketRocket dependency used by Ably.

This is blocking us from submitting our App to AppStore, please resolve this as soon as possible.

**Comment by mattheworiordan** [comment]
@hliu2000 that's an odd one, we've not had that reported before.  We're assigning to two of our iOS engineers to comment.

**Comment by ricardopereira** [comment]
@funkyboy Any idea? 

SocketRocket has the key https://github.com/facebook/SocketRocket/blob/28035e1a98a427853e4038ff1b70479fa8374cfa/SocketRocket/Resources/Info.plist#L21-L22

Maybe a Carthage issue.

**Comment by ricardopereira** [comment]
It seems a known issue 😕 https://github.com/facebook/SocketRocket/issues/591

**Comment by funkyboy** [comment]
See https://github.com/ably/ably-ios/issues/701

**Comment by ricardopereira** [comment]
@funkyboy Thanks! That's it 💪

So the workaround is changing the `Carthage/Build/iOS/SocketRocket.framework/Info.plist` file? Is this enough?

**Comment by ricardopereira** [comment]
Ok, thanks.

@hliu2000 could you please try setting the `CFBundleVersion` to 1.0.0 from `Carthage/Build/iOS/SocketRocket.framework/Info.plist` and try submit the app again?

**Comment by hliu2000** [comment]
Hi Ricardo,
I could try that, but it won't work for our CI system since the
Carthage/Build/iOS
folder is generated. Also I don't want to hack our CI system for this.
I know this is a work around, but will this problem been solved in next
Ably version? Other developer using Ably will have the same problem anyway.
It will be great if you can provide a time estimate about when this can be
solved.

**Comment by mattheworiordan** [comment]
@hliu2000 I know we've been talking about replacing SocketRocket completely as it's no longer actively maintained.  We'll back to you with a plan soon.

**Comment by hliu2000** [comment]
That's great, thanks a lot.

**Comment by mattheworiordan** [comment]
Hey @hliu2000.  We have chatted internally, and believe we'll go with a short term fix so that you can get this deployed now, and then look at a longer term solution for SocketRocket.

Short term fix will require us to fork SocketRocket, and also address https://github.com/ably/ably-ios/issues/804. We'll do that ASAP.

Longer term fix is to replace SocketRocket completely, see https://github.com/ably/ably-ios/issues/805.

We'll give you an update shortly.

**Comment by hliu2000** [comment]
Thanks, really appreciated.

**Comment by ricardopereira** [comment]
@hliu2000 Patch has been released and tested https://github.com/ably/ably-ios/releases/tag/1.1.1.

**Comment by funkyboy** [comment]
Closing this. Feel free to reopen as you see fit.
