### ISSUE TITLE
Can't be integrated as Cocoapods static library 

### ISSUE THREAD

**Issue by torianin** [ably/ably-ios#822]
### Which version of the Ably SDK are you using? 
1.1.2

### Are you using Cocoapods? 
1.6.0.beta.2

### Which version of Xcode are you using? 
Xcode 10.1
Build version 10B61

### What did you expect to happen?
Project to build successfully when using `use_frameworks!`

### What happened instead?
![image](https://user-images.githubusercontent.com/2284808/50505882-43b70f80-0a76-11e9-976a-6a1f1af012b2.png)

**Comment by ricardopereira** [comment]
Hello @torianin, sorry for the late reply. Could you share your `Podfile` please?

**Comment by ricardopereira** [comment]
Feel free to open this issue if the problem persists.
