### ISSUE TITLE
Rest: message encoding

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#95]
I am implementing [RSL4a](http://docs.ably.io/client-lib-development-guide/features/#RSL4a).
> Payloads must be binary, strings, or objects capable of JSON representation, or can be empty (omitted). Any other data type should not be permitted and an exception should be raised

Well, I dig into it and I found **two places** to setup the **encoding** (one for the payload and one for the client messages):
```
ARTChannel.payloadEncoder //I don't understand this property. Isn't supposed to encode the payload from the data type?
```
```
ARTRest.defaultEncoder //Message encoder
```

There are 4 payload encoders:
 - `ARTBase64PayloadEncoder`
 - `ARTUtf8PayloadEncoder`
 - `ARTJsonPayloadEncoder`
 - `ARTCipherPayloadEncoder`

and one `ARTPayloadEncoderChain` that allows "multi-encoding".

### ARTChannel
When a `ARTChannel` is created it uses a private payload encoder  `[ARTPayload defaultPayloadEncoder]` ~~and I my opinion it is supposed to use the `ARTRest.defaultEncoder`~~. The private payload encoder (`ARTChannel.payloadEncoder`) is used to encode/decode the messages.

The `[ARTPayload defaultPayloadEncoder]` is an `[ARTJsonPayloadEncoder instance]` when the `cipherParams` is empty. If it is not then it uses a `ARTPayloadEncoderChain` with `ARTJsonPayloadEncoder`, `ARTUtf8PayloadEncoder` and finally `ARTCipherPayloadEncoder`.

### ARTMessage
The `ARTMessage` when it is created it initialises the payload with an _empty one_ where the encoding is nothing (`[ARTPayload payloadWithPayload:data encoding:@""]`).

### ARTRest
The `defaultEncoder` is always an `ARTJsonEncoder` and it is used to publish a message (`[rest.defaultEncoder encodeMessage:message]`).

**Comment by ricardopereira** [comment]
@mattheworiordan I need some orientation with this. I don't know what makes sense or not.

**Comment by ricardopereira** [comment]
Test with presence fixtures `jsonCommon["post_apps"]["channels"][0]["presence"]`

```
encoding: empty
expected: Bool
data: Optional(true) //Boolean

encoding: json/utf-8
expected: JSONObject
data: Optional({"example":{"json":"Object"}}) //JSON Object

encoding: json/utf-8/cipher+aes-128-cbc/base64
expected: NSData
data: Optional(<1cee1c61 23fc2f26 cf6013d9 3c740eb6 e0f9df2a c3dd8577 341a1311 8061e14d 0dd505c7 6ed91fb0 37d3b292 9e2d016d>) //AES-128

encoding: empty
expected: NSNumber
data: Optional(24) //Number

encoding: empty
expected: JSONObject
data: Optional({ "test": "This is a JSONObject clientData payload"}) //Decoded

encoding: empty
expected: NSString
data: Optional(This is a string clientData payload) //UTF8
```

**Comment by mattheworiordan** [comment]
@ricardopereira lets chat tomorrow, probably easier to talk this through.

**Comment by tcard** [comment]
This has changed completely with #171. `payloadEncoder` and children are gone, now we have a single `dataEncoder` and the only state it has is the cipher params. Should I close?
